package com.jb.radar;
import java.util.*;
public class AIBehaviorTest {
 static void ok(boolean b,String s){if(!b)throw new AssertionError(s);}static class Certain extends Random{private static final long serialVersionUID=1;public double nextDouble(){return 0;}public double nextGaussian(){return 0;}}
 static Game fixture(){Game g=new Game(5);g.start();g.contacts.clear();g.random=new Certain();return g;}
 static Game.Contact plane(Game g,int smart){Game.Contact t=GameTest.target(g,0);g.ai.assign(t,smart,2,2);t.weapon=-1;return t;}
 public static void main(String[] args){
  Game g=fixture();Game.Contact t=plane(g,5);ok(!g.ai.warn(t,PilotAI.Warning.TRACK,true)&&t.pilot.cues.isEmpty(),"silent tracking remains hidden");ok(!g.ai.warn(t,PilotAI.Warning.LOCK,false),"undetectable lock hidden");ok(g.ai.warn(t,PilotAI.Warning.LOCK,true),"detectable lock queued");g.ai.tick(t,.05);ok(t.pilot.state==PilotAI.State.APPROACH&&t.pilot.cues.size()==1,"no immediate response");g.elapsed=2;g.ai.tick(t,.05);ok(t.pilot.cues.isEmpty(),"warning delivered after delay");ok(PilotAI.reactionDelay(1,PilotAI.Warning.LAUNCH)>PilotAI.reactionDelay(5,PilotAI.Warning.LAUNCH),"smart reaction delay");ok(PilotAI.recognitionChance(1,PilotAI.Warning.LOCK)<PilotAI.recognitionChance(5,PilotAI.Warning.LOCK),"smart warning recognition");
  g=fixture();t=plane(g,5);t.x=2;t.y=0;ok(!g.releaseBombs(t)&&g.bombs.isEmpty(),"release needs a valid speed/altitude/heading solution");t.speed=600;t.alt=Game.terrain(0,0)+2000;t.x=g.aircraft(t).preset.leadKm(2000,t.speed);t.heading=-Math.PI/2;t.aimStableSeconds=2;t.pilot.state=PilotAI.State.EVADE;ok(!g.releaseBombs(t),"evasion cancels release");t.pilot.state=PilotAI.State.APPROACH;ok(g.releaseBombs(t)&&g.bombs.size()==1&&t.pilot.bombs==1&&t.pilot.state==PilotAI.State.ATTACK_RUN,"valid ballistic release consumes one configured bomb");ok(!g.releaseBombs(t),"release cooldown prevents instantaneous full load");g.elapsed+=.36;ok(g.releaseBombs(t)&&g.bombs.size()==2&&t.pilot.bombs==0&&t.pilot.state==PilotAI.State.EXIT,"last weapon starts exit");ok(!g.releaseBombs(t),"cannot release exhausted weapons");Game.Bomb b=g.bombs.get(0);double impactX=b.impactX,impactY=b.impactY;g.flyBomb(b,.1);ok(b.alive&&g.battery.condition()==100,"bomb takes time to fall");t.x=25;t.heading=2;g.flyBomb(b,.1);ok(b.impactX==impactX&&b.impactY==impactY&&Math.abs(b.x-b.startX-b.vx*b.age)<1e-9,"unguided trajectory independent of later aircraft actions");b.vx+=.3;for(int step=0;step<800&&b.alive;step++)g.flyBomb(b,.05);ok(!b.alive&&g.battery.condition()==100,"a dispersed release trajectory can miss");Game.Bomb other=g.bombs.get(1);for(int step=0;step<800&&other.alive;step++)g.flyBomb(other,.05);ok(g.battery.condition()<100&&g.ai.bombRuns==1&&g.ai.damagingRuns==1,"assess completed airborne bomb group once");
  g=fixture();t=plane(g,3);g.damageAircraft(t,75);ok(g.ai.isExiting(t)&&!g.ai.canBomb(t),"critical damage disengages without dropping");Game.Contact empty=plane(g,2);empty.pilot.bombs=0;g.ai.tick(empty,.1);ok(g.ai.isExiting(empty),"exhausted armed aircraft disengages");t=plane(g,4);g.ai.abort(t);g.elapsed=7;g.ai.tick(t,.1);ok(t.pilot.state==PilotAI.State.REASSESS,"aborted pass waits for safe clear then reassesses");g.elapsed=9.1;g.ai.tick(t,.1);ok(t.pilot.state==PilotAI.State.REPOSITION,"safe surviving armed aircraft circles back");t.x=t.pilot.wayX;t.y=t.pilot.wayY;g.elapsed+=.3;g.ai.tick(t,.1);ok(t.pilot.state==PilotAI.State.APPROACH,"retries approach");
  g=fixture();t=plane(g,5);double initial=g.ai.caution(t.pilot);g.ai.recordFire(t.pilot,18);double once=g.ai.caution(t.pilot);for(int i=0;i<200;i++)g.ai.recordFire(t.pilot,18);ok(initial==0&&once>0&&once<g.ai.caution(t.pilot)&&g.ai.caution(t.pilot)<=.31,"gradual bounded adaptation");ok(g.ai.side.early==32&&g.ai.side.repeated==32,"bounded counters");Game.Contact rookie=plane(g,1);ok(g.ai.caution(rookie.pilot)==0,"learning limited by Smart Level");
  Properties props=new Properties();props.setProperty("ai.sharedMemory","false");Game privateGame=new Game(8,new Economy(new Economy.MemoryStore()),Equipment.defaults(),new CombatRules(props));privateGame.start();Game.Contact a=plane(privateGame,5),c=plane(privateGame,5);privateGame.ai.recordFire(a.pilot,18);ok(privateGame.ai.caution(a.pilot)>0&&privateGame.ai.caution(c.pilot)==0&&privateGame.ai.side.early==0,"sharing can be disabled");
  g=fixture();t=plane(g,5);g.ai.react(t,PilotAI.Warning.LAUNCH);int action=t.pilot.lastAction.ordinal();ok(t.pilot.learnReaction,"reaction starts observation window");g.elapsed=5;g.ai.tick(t,.1);ok(g.ai.side.success[action]==0,"no premature learning from hidden missile state");g.elapsed=13;g.ai.tick(t,.1);ok(g.ai.side.success[action]==1,"surviving observed threat window records outcome");g.ai.react(t,PilotAI.Warning.LAUNCH);action=t.pilot.lastAction.ordinal();g.confirmIntercept(t,false);ok(g.ai.side.failure[action]==1,"destruction records failed reaction");g.start();ok(g.ai.side.early==0&&g.ai.side.success[action]==0&&g.ai.bombRuns==0,"mission resets learning");
  System.out.println("PASS: silent/delayed cues, Smart levels, ballistic release/cooldown, flight/scatter, critical disengagement/safe retry, bounded optional shared memory and reset");
 }
}
