package com.jb.radar;
import java.util.Random;
/** Perceived-evidence decisions and timers; no tests inject hidden weapon truth into the pilot. */
public final class AIUpdateTest {
 static class Fixed extends Random {private static final long serialVersionUID=1L;final double value;Fixed(double v){value=v;}public double nextDouble(){return value;}public double nextGaussian(){return 0;}}
 static void ok(boolean b,String text){if(!b)throw new AssertionError(text);}
 static Game game(){Game g=new Game(20);g.start();g.contacts.clear();g.enemyMissiles.clear();g.random=new Fixed(0);return g;}
 static Game.Contact plane(Game g,int smart){Game.Contact t=GameTest.target(g,0);t.x=30;t.speed=650;t.heading=-Math.PI/2;t.weapon=-1;g.ai.assign(t,smart,4,1);g.ai.configure(t,g.aircraft.profile(0));return t;}
 static void at(Game g,Game.Contact t,double now){g.elapsed=now;g.ai.tick(t,.25);}
 static void observe(Game g,Game.Contact t,PilotAI.Warning w,String id,double bearing,double until){g.ai.observe(t,w,id,bearing,1,until);}
 public static void main(String[] args){
  Game g=game();Game.Contact t=plane(g,5);ok(!g.ai.observe(t,PilotAI.Warning.TRACK,"silent",0,1,10),"TWS never becomes pilot evidence");
  observe(g,t,PilotAI.Warning.SEARCH,"receiver-1",.3,8);double due=t.pilot.cues.get(0).due;ok(due>=2&&due<=4,"normal delay is 2–4 seconds after receiver");at(g,t,due-.01);ok(t.pilot.awareness==PilotAI.Awareness.UNAWARE,"no immediate search reaction");at(g,t,due+.01);ok(t.pilot.state==PilotAI.State.CAUTIOUS&&!g.ai.shouldCountermeasure(t),"search only causes caution, no countermeasures");
  double before=t.pilot.stateSince;for(int i=0;i<20;i++)observe(g,t,PilotAI.Warning.SEARCH,"receiver-1",.3,8);ok(t.pilot.cues.isEmpty()&&t.pilot.stateSince==before,"repeated search does not generate panic decisions");
  observe(g,t,PilotAI.Warning.LOCK,"receiver-1",.4,10);double lockDue=t.pilot.cues.get(0).due;g.elapsed+=.1;observe(g,t,PilotAI.Warning.LOCK,"receiver-1",.4,10.1);ok(t.pilot.cues.get(0).due==lockDue,"refresh never rearms reaction delay");
  observe(g,t,PilotAI.Warning.ACTIVE_SEEKER,"receiver-2",1,11);double emergency=0;for(PilotAI.Cue c:t.pilot.cues)if(c.kind==PilotAI.Warning.ACTIVE_SEEKER)emergency=c.due;ok(emergency-g.elapsed>=1&&emergency-g.elapsed<=2&&emergency<lockDue,"new urgent evidence interrupts slower lock decision");at(g,t,emergency+.01);ok(t.pilot.state==PilotAI.State.MISSILE_EVASION,"credible seeker warning causes delayed evasion");double heading=g.ai.heading(t);at(g,t,emergency+.5);ok(g.ai.heading(t)==heading,"maneuver held between assessments");
  // Multiple same-urgency bearings are combined, not reduced to hidden nearest-missile truth.
  g=game();t=plane(g,5);observe(g,t,PilotAI.Warning.ACTIVE_SEEKER,"a",0,5);observe(g,t,PilotAI.Warning.ACTIVE_SEEKER,"b",Math.PI,5);at(g,t,1.1);ok(Double.isNaN(t.pilot.selectedBearing),"opposite perceived threats use uncertain broad compromise");
  // Republishing a receiver's memory is not a new observation and does not extend 12-second missile memory.
  g=game();t=plane(g,5);observe(g,t,PilotAI.Warning.ILLUMINATION,"same-emitter",.2,8);at(g,t,1.1);for(int i=2;i<=8;i++){g.elapsed=i;observe(g,t,PilotAI.Warning.ILLUMINATION,"same-emitter",.2,8);}double expiry=0;for(PilotAI.Evidence e:t.pilot.evidence.values())if(e.kind==PilotAI.Warning.ILLUMINATION)expiry=e.expiresAt;ok(expiry==12,"remembered RF observation is not refreshed every frame");
  g.elapsed=9;observe(g,t,PilotAI.Warning.SEARCH,"same-emitter",.2,40);at(g,t,12.1);ok(g.ai.defensive(t),"old guidance warning expires but defense keeps safe-clear delay");at(g,t,18.2);ok(!g.ai.defensive(t),"search cannot hold a dead guidance warning forever");at(g,t,20.3);ok(t.pilot.state!=PilotAI.State.REASSESS,"low search warning cannot freeze post-defense recovery");
  // After every relevant cue has expired, six clear seconds precede reassessment and any retry.
  g=game();t=plane(g,5);observe(g,t,PilotAI.Warning.VISUAL_MISSILE,"visual-1",.2,3);at(g,t,1.1);at(g,t,12.1);at(g,t,18);ok(g.ai.defensive(t),"full safe-clear cooldown held");at(g,t,18.3);ok(t.pilot.state==PilotAI.State.REASSESS,"safe-clear leads to reassessment");at(g,t,20.3);ok(t.pilot.state==PilotAI.State.APPROACH,"reassess recovers normal route");
  // No-bomb intrusion is a valid mission, but a depleted attack aircraft leaves.
  g=game();t=plane(g,5);g.ai.configure(t,g.aircraft.profile(AircraftProfiles.MIG25));at(g,t,1);ok(t.pilot.intrusion&&t.pilot.bombs==0&&!g.ai.isExiting(t)&&!g.ai.canBomb(t),"WP-0 is not out of bombs");t.x=t.pilot.intrusionX;t.y=t.pilot.intrusionY;at(g,t,2);ok(g.ai.isExiting(t),"intrusion follows configured route then exits");
  t=plane(g,5);t.pilot.health=34;at(g,t,3);ok(g.ai.isExiting(t)&&!g.ai.canBomb(t),"under 35 percent health permanently disengages");observe(g,t,PilotAI.Warning.VISUAL_MISSILE,"pursuer",1,8);at(g,t,4.1);ok(g.ai.isExiting(t)&&g.ai.defensive(t),"disengaging aircraft can still defend without resuming attack");
  g=game();t=plane(g,5);g.ai.abort(t);ok(t.pilot.passes==1&&!g.ai.isExiting(t),"one disrupted approach permits retry");t.pilot.passDisrupted=false;g.ai.abort(t);ok(t.pilot.passes==2&&g.ai.isExiting(t),"two disrupted approaches end attack");
  // Combined countermeasure inventory/cooldown/reserve use only reacted evidence.
  g=game();t=plane(g,5);t.pilot.countermeasures=12;t.pilot.countermeasureCapacity=60;t.pilot.countermeasureRequested=true;ok(!g.ai.shouldCountermeasure(t),"request without perceived threat cannot spend rounds");observe(g,t,PilotAI.Warning.ILLUMINATION,"rf",1,20);at(g,t,1.1);ok(g.ai.shouldCountermeasure(t)&&t.pilot.countermeasures==9,"suspected guidance permits one three-unit burst");t.pilot.countermeasureRequested=true;ok(!g.ai.shouldCountermeasure(t)&&t.pilot.countermeasures==9,"same instant cannot spend second burst");at(g,t,3.7);ok(g.ai.shouldCountermeasure(t)&&t.pilot.countermeasures==6,"cooldown and next assessment permit next burst");at(g,t,6.3);ok(!g.ai.shouldCountermeasure(t)&&t.pilot.countermeasures==6,"suspected guidance preserves ten-percent reserve");observe(g,t,PilotAI.Warning.VISUAL_MISSILE,"confirmed",1,20);at(g,t,7.4);t.pilot.countermeasureRequested=true;ok(g.ai.shouldCountermeasure(t)&&t.pilot.countermeasures==3,"credible immediate threat may spend reserve");at(g,t,10);t.pilot.countermeasureRequested=true;ok(g.ai.shouldCountermeasure(t)&&t.pilot.countermeasures==0,"reserve is finite");at(g,t,13);ok(!g.ai.shouldCountermeasure(t),"empty countermeasures never regenerate");
  // Hidden impact results cannot teach surviving pilots or shared squadron memory.
  g=game();t=plane(g,5);g.ai.released(t,2);g.ai.bombOutcome(t,40,false);g.ai.bombOutcome(t,0,true);ok(g.ai.bombRuns==1&&g.ai.damagingRuns==1,"actual impact feeds only debrief counters");ok(t.pilot.memory.runs==0&&g.ai.side.runs==0,"partly unseen run cannot learn an exact hit or miss");
  t=plane(g,5);g.ai.released(t,2);g.ai.bombOutcome(t,0,false);g.ai.bombOutcome(t,5,true);ok(t.pilot.memory.runs==1&&t.pilot.memory.damageRuns==1,"observed successful impact supplies legitimate outcome evidence");
  t=plane(g,5);g.ai.released(t,2);g.ai.bombOutcome(t,0,true);g.ai.bombOutcome(t,0,true);ok(t.pilot.memory.runs==1&&t.pilot.memory.failedRuns==1,"fully observed misses can inform the next approach");
  // Rookie delay and missed recognition preserve Mission 1 accessibility.
  g=game();t=plane(g,1);g.random=new Fixed(.3);ok(!g.ai.observe(t,PilotAI.Warning.LOCK,"missed",0,1,8),"rookie can miss credible lock warning");g.random=new Fixed(0);observe(g,t,PilotAI.Warning.VISUAL_MISSILE,"noticed",0,8);ok(t.pilot.cues.get(0).due>=1.6,"rookie emergency reaction is near slow end of allowed range");
  // Pilot skill affects processing/execution only; it does not modify receiver or flight configuration.
  g=game();t=plane(g,3);g.random=new Fixed(.6);t.pilot.skill=0;ok(!g.ai.observe(t,PilotAI.Warning.LOCK,"low-skill",0,1,8),"low configured skill can mishandle warning evidence");t.pilot.skill=1;ok(g.ai.observe(t,PilotAI.Warning.LOCK,"high-skill",0,1,8),"higher configured skill improves processing with same sensor evidence");g.random=new Fixed(0);
  g.ai.developmentTraceEnabled=true;observe(g,t,PilotAI.Warning.SEARCH,"debug",0,8);ok(!t.pilot.developmentTrace.isEmpty(),"optional development trace records evidence");ok(!g.log.toString().contains("debug"),"pilot diagnostic evidence does not leak into player battle log");
  System.out.println("PASS: delayed perceived warnings, TWS silence, stable multi-threat maneuvers, independent warning/missile memory, safe-clear, WP-0, abort thresholds, finite countermeasures, rookies and private trace");
 }
}
