package com.jb.radar;
public class AutoTrackingTest {
 static void ok(boolean b,String s){if(!b)throw new AssertionError(s);}
 static Game game(int slots){Game g=EquipmentTest.game(EquipmentTest.config("radar.retainTracks","false","radar.tracks",""+slots,"radar.channels",""+Math.min(2,slots),"missile.rampart.radarMode","ACTIVE"));g.random=new AIBehaviorTest.Certain();g.elapsed=1;return g;}
 static Game.Contact add(Game g,int id,double range){Game.Contact t=new Game.Contact();t.id=id;t.x=range-.2;t.alt=3000;t.speed=720;t.heading=Math.PI/2;t.weapon=-1;g.contacts.add(t);g.observe(t);g.elapsed+=1;t.x=range;g.observe(t);return t;}
 public static void main(String[] args){
  Game g=game(3);Game.Contact acquiring=new Game.Contact();acquiring.id=50;acquiring.x=5;acquiring.alt=3000;g.contacts.add(acquiring);g.observe(acquiring);ok(g.trackStage(acquiring)==Game.TrackStage.ACQUIRING&&!g.stableTrack(acquiring)&&g.speedText(acquiring).equals("---")&&g.directionText(acquiring).equals("---")&&g.launchBlock(acquiring).equals("TRACK TOO WEAK"),"first detection acquires without motion or firing solution");g=game(3);Game.Contact[] t=new Game.Contact[6];for(int i=0;i<6;i++)t[i]=add(g,i+1,5+i*2);
  ok(g.trackedCount()==3,"capacity 3 of 6");for(int i=0;i<6;i++){ok(g.visible(t[i]),"all six visible");ok(g.tracked(t[i])==(i<3),"closest aircraft first");ok(g.speedText(t[i]).equals("---")== (i>=3),"speed only tracked");ok(g.altitudeText(t[i]).equals("---")== (i>=3),"altitude only tracked");ok(g.directionText(t[i]).equals("---")== (i>=3),"direction only tracked");}
  double old=g.displayX(t[5]),oldRange=g.displayRange(t[5]);g.elapsed+=4;for(Game.Contact c:t){c.x+=40;c.alt=8000;c.speed=2000;c.heading=-1;}
  ok(g.displayX(t[5])==old&&g.displayRange(t[5])==oldRange,"untracked frozen even when truth changes");ok(Math.abs(g.displayX(t[0])-(t[0].px+.2*g.predictionAge(t[0])))<1e-9&&t[0].palt==3000&&Math.abs(t[0].pspeed-720)<1e-8,"prediction from cached estimate, no live truth");
  g=game(3);for(int i=0;i<6;i++)t[i]=add(g,i+1,5+i*2);Game.EnemyMissile incoming=new Game.EnemyMissile();incoming.id=101;incoming.weapon=4;incoming.x=20;incoming.alt=3000;incoming.z=3;incoming.speed=.3;incoming.flight.vx=-1;g.enemyMissiles.add(incoming);g.observe(incoming);
  ok(g.tracked(incoming)&&g.tracked(t[0])&&g.tracked(t[1])&&!g.tracked(t[2]),"incoming missile ahead of nearer aircraft");
  g.prioritize(t[5]);ok(g.tracked(t[5])&&g.tracked(incoming)&&g.tracked(t[0])&&!g.tracked(t[1])&&g.trackedCount()==3,"manual priority evicts lowest eligible track");g.prioritize(t[5]);ok(!t[5].priority&&!g.tracked(t[5])&&g.tracked(t[1]),"clear priority restores automatic ranking");
  g=game(2);Game.Contact a=add(g,1,5),b=add(g,2,6),c=add(g,3,12);GameTest.lock(g,a);g.launch(b);ok(g.hardLocked(a)&&g.inbound(b)==1,"fixture lock plus active engagement");ok(g.prioritize(c).contains("NO FREE TRACK SLOT")&&!c.priority&&!g.tracked(c),"cannot evict lock or engagement");g.release(a);g.prioritize(c);ok(g.tracked(c)&&g.tracked(b)&&!g.tracked(a),"replace unprotected only");g.confirmIntercept(c,false);ok(g.tracked(a)&&!g.tracked(c)&&g.trackedCount()==2,"destruction immediately refills slot");
  g=game(1);a=add(g,1,5);c=add(g,2,12);g.elapsed=a.seen+10;a.alt=20;g.observe(a);ok(g.stale(a)&&g.tracked(a)&&!g.liveTrack(a)&&g.trackState(a).equals("COASTING"),"missed sweep stale but retains track temporarily");double frozen=g.displayX(a);g.elapsed=a.seen+17;g.maintainTracks();ok(Math.abs(g.displayX(a)-(frozen+7*Math.sin(a.pheading)*a.pspeed/3600))<1e-8&&g.altitudeText(a).equals("3000"),"coasting position uses cached motion and altitude remains stale");ok(g.launchBlock(a).equals("TRACK TOO WEAK"),"stale track cannot support new active shot");g.elapsed=a.seen+22.1;c.alt=3000;g.observe(c);g.maintainTracks();ok(!g.tracked(a)&&g.tracked(c)&&g.visible(a),"expired track frees slot, detection stays briefly as stale plot");ok(g.speedText(a).equals("---"),"expired track hides detail");g.elapsed=a.seen+33;ok(!g.visible(a),"old contact eventually disappears");
  g=game(1);a=add(g,1,5);GameTest.lock(g,a);g.elapsed=a.seen+10;a.alt=20;g.observe(a);g.maintainTracks();g.elapsed+=g.equipment.radar.lockLossSeconds+.01;g.maintainTracks();ok(!g.hardLocked(a)&&!a.illuminated&&g.channels()==0,"missed sweep clears stale lock after loss tolerance");a.alt=3000;g.elapsed+=1;g.observe(a);ok(g.liveTrack(a)&&!g.hardLocked(a)&&a.missed==0,"reacquisition refreshes without auto locking");
  g=game(2);g.range=10;a=add(g,1,18);ok(a.samples==2&&g.tracked(a)&&!g.visible(a),"display zoom does not reduce sensor detection");g.range=30;ok(g.visible(a),"zoom out reveals cached detection");a.x=37;g.elapsed=a.seen+10;g.observe(a);ok(a.samples==2&&g.stale(a),"detection range remains enforced");
  // Search detections gathered without a tracking slot must not become perfect motion instantly.
  g=game(1);a=add(g,1,4);b=add(g,2,12);for(int i=0;i<4;i++){g.elapsed+=1;b.x-=.1;g.observe(b);}ok(!g.tracked(b)&&g.speedText(b).equals("---"),"full-capacity search contact remains detection-only");g.prioritize(b);ok(g.tracked(b)&&!g.stableTrack(b)&&g.speedText(b).equals("---")&&g.directionText(b).equals("---"),"newly assigned slot requires its own observations before revealing motion");for(int i=0;i<2;i++){g.elapsed+=1;b.x-=.1;g.observe(b);}ok(g.stableTrack(b)&&!g.speedText(b).equals("---"),"two actual tracked revisits establish a motion estimate");
  // Live tick path: neither prioritized aircraft nor missiles get between-sweep refreshes.
  g=game(3);a=add(g,1,8);g.prioritize(a);incoming=new Game.EnemyMissile();incoming.id=101;incoming.weapon=4;incoming.x=8;incoming.alt=3000;incoming.z=3;incoming.speed=.18;incoming.flight.vx=-1;g.enemyMissiles.add(incoming);g.observe(incoming);g.sweep=3;int as=a.samples,ms=incoming.samples;double ax=a.px,mx=incoming.px;
  for(int i=0;i<10;i++)g.tick(.05);ok(a.samples==as&&incoming.samples==ms&&a.px==ax&&incoming.px==mx,"all contacts refresh only when beam reaches them");
  g.battery.parts[Battery.POWER].hp=0;g.maintainTracks();ok(g.trackedCount()>0&&g.stale(a)&&!g.liveTrack(a)&&g.visible(a),"offline radar coasts cached tracks without live measurements");g.elapsed+=g.trackExpiry()+.01;g.maintainTracks();ok(g.trackedCount()==0,"offline track timeout eventually frees slots");
  System.out.println("PASS: automatic 3/6 capacity, detection-only displays, measurement prediction, missile/manual priority, protected engagements, destruction/expiry refill, stale freeze/reacquisition, scan-only updates and display zoom independence");
 }
}
