package com.jb.radar;
import java.util.*;import java.io.*;
public class DamageTest {
 static void ok(boolean b,String s){if(!b)throw new AssertionError(s);}static void eq(double a,double b,String s){ok(Math.abs(a-b)<1e-8,s+" "+a+" / "+b);}
 public static void main(String[] args)throws Exception{
  CombatRules r=CombatRules.defaults();Battery b=new Battery(r);eq(b.explode(0,0,40,.01,0),40*.55*.65/7,"average is not a repeated health pool");eq(b.parts[0].hp,100-40*.55*.65,"full direct damage");for(int i=1;i<b.parts.length;i++)eq(b.parts[i].hp,100,"outside radius untouched");b.reset();b.explode(.005,0,40,.01,0);eq(b.parts[0].hp,100-40*.55*.65*.5,"half-radius falloff");b.reset();eq(b.explode(5,5,1554.5,.9,0),0,"distant bomb misses");
  Properties p=new Properties();p.setProperty("component.0.protection","0");b=new Battery(new CombatRules(p));b.explode(0,0,100,.01,0);eq(b.parts[0].hp,100,"zero protection factor shields component");
  Game g=new Game(42);g.start();Game.Contact t=GameTest.target(g,0);GameTest.lock(g,t);ok(t.illuminated,"healthy lock");Battery.Component power=g.battery.parts[Battery.POWER];g.explode(power.x,power.y,100,.01,"TEST");ok(!g.battery.powered(g.elapsed)&&!t.illuminated,"power hit interrupts and loses lock");ok(g.battery.powered(10),"temporary power restores");g.elapsed=10;g.battery.parts[Battery.L1].hp=50;g.launchers[0].reload=90;eq(g.reloadSeconds(0),180,"damaged launcher reload doubles");g.battery.parts[Battery.L1].hp=0;g.syncBattery();ok(g.launchers[0].ammo==0&&g.lostAmmo==3&&g.launchBlock(t).equals("LAUNCHER DISABLED"),"dead launcher disabled and ammo accounted");g.battery.parts[Battery.COMMAND].hp=40;ok(g.battery.processingDelay()>2,"command damage slows observations");
  for(int i=0;i<7;i++)eq(r.explosiveKg[i],CombatRules.KG[i],"specified bomb kg");Equipment e=Equipment.defaults();ok(e.enemy[0].explosiveKg!=e.enemy[0].massKg,"warhead is separate from total mass");p=new Properties();p.setProperty("missile.kh25.massKg","200");Equipment changed=new Equipment(p);eq(changed.enemy[0].explosiveKg,e.enemy[0].explosiveKg,"mass cannot change explosive damage");
  try(InputStream in=new FileInputStream("assets/combat.properties")){CombatRules loaded=CombatRules.load(in);eq(loaded.multiplier,r.multiplier,"bundled balance file");}p=new Properties();p.setProperty("damage.multiplier","NaN");try{new CombatRules(p);throw new AssertionError("invalid balance accepted");}catch(IllegalArgumentException expected){}
  System.out.println("PASS: explosive kg, falloff, protection, component isolation, power outages, reload degradation, config validation");
 }
}
