package com.jb.radar;
public class EconomyTest {
 static void ok(boolean b,String s){if(!b)throw new AssertionError(s);}
 static class FailingStore extends Economy.MemoryStore {boolean fail;public boolean save(Economy.State s){return !fail&&super.save(s);}}
 public static void main(String[] args){Economy.MemoryStore store=new Economy.MemoryStore();Economy e=new Economy(store);ok(e.snapshot().dollars==0&&e.snapshot().bp==0,"fresh balances");ok(!e.intercept("T-1",false),"no payout outside mission");e.beginMission();e.intercept("T-1",false);e.intercept("M-1",true);ok(!e.intercept("T-1",false),"no duplicate kill payout");ok(e.snapshot().dollars==400&&e.snapshot().bp==175,"combat rewards");e.finish(true,3);Economy.State s=e.snapshot();ok(s.dollars==1200&&s.bp==575&&s.missionDollars==1200&&s.missionBP==575,"victory and surviving hit rewards");e.finish(true,4);e.finish(false,0);ok(e.snapshot().dollars==1200&&e.snapshot().completed==1,"finish exactly once");e=new Economy(store);ok(e.snapshot().dollars==1200&&e.snapshot().wins==1,"reload persisted wallet and receipt");e.beginMission();e.intercept("T-1",false);e.finish(false,0);ok(e.snapshot().dollars==1450&&e.snapshot().bp==675&&e.snapshot().missionDollars==250,"defeat retains combat rewards only");e.beginMission();e.intercept("M-1",true);e.abandon();e=new Economy(store);ok(e.snapshot().dollars==1600&&"WITHDREW".equals(e.snapshot().result),"withdraw keeps rewards");e.beginMission();e.intercept("T-2",false);e=new Economy(store);ok("INTERRUPTED".equals(e.snapshot().result)&&e.snapshot().dollars==1850,"process loss preserves earned balance");e.finish(true,4);ok(e.snapshot().dollars==1850,"no victory bonus for interrupted mission");
 FailingStore fs=new FailingStore();e=new Economy(fs);e.beginMission();fs.fail=true;e.intercept("T-1",false);ok(e.saveFailed&&e.snapshot().dollars==250,"save failure visible and pending");ok(!e.beginMission(),"cannot erase pending reward on restart");e.intercept("T-1",false);fs.fail=false;ok(e.flush(),"save retry");e=new Economy(fs);ok(e.snapshot().dollars==250,"retry credits once");fs.fail=true;Game g=new Game(4,e);ok(!g.start()&&!g.running,"failed start does not launch mission");fs.fail=false;ok(g.start(),"can start after recovery");
 g.contacts.clear();Game.Contact t=GameTest.target(g,0);long before=e.snapshot().dollars;g.illuminate(t);g.launch(t);Game.Missile m=g.missiles.get(0);for(int i=0;i<600&&m.alive;i++)g.fly(m,.1);ok(e.snapshot().dollars==before+250&&e.snapshot().aircraft==1,"radar interception banks aircraft reward");g.confirmIntercept(t,true);ok(e.snapshot().aircraft==1,"same destroyed contact cannot pay twice");
 java.util.Properties irConfig=new java.util.Properties();irConfig.setProperty("radar.infrared","true");irConfig.setProperty("radar.irLockKm","9");g=new Game(4,e,new Equipment(irConfig));g.start();g.contacts.clear();Game.EnemyMissile incoming=new Game.EnemyMissile();incoming.id=101;incoming.weapon=4;incoming.x=incoming.px=4;incoming.alt=incoming.palt=1800;incoming.z=1.8;incoming.samples=4;incoming.priority=false;incoming.radarTracked=true;incoming.seen=g.elapsed;g.enemyMissiles.add(incoming);g.toggleWeapon();g.weaponLock(incoming);for(int i=0;i<70;i++)g.ir.tick(.05);g.fireWeapon(incoming);m=g.missiles.get(0);before=e.snapshot().dollars;for(int i=0;i<1200&&m.alive;i++){g.elapsed+=.02;g.fly(m,.02);if(incoming.alive)g.flyEnemy(incoming,.02);}ok(e.snapshot().dollars==before+150&&e.snapshot().missiles==1,"IR interception banks missile reward");g.finish(false);long total=e.snapshot().dollars;g.finish(true);ok(e.snapshot().dollars==total,"game finish cannot pay twice");ok(Economy.add(Long.MAX_VALUE-1,250)==Long.MAX_VALUE,"large balances do not overflow");System.out.println("PASS: combat/victory rewards, defeat/withdrawal, persistence/recovery, duplicate protection, failed-write retry, radar+IR payouts and overflow");}
}
