package com.jb.radar;
import java.util.*;import java.io.*;
public class EquipmentTest {
 static void check(boolean b,String m){if(!b)throw new AssertionError(m);}
 static Equipment config(String... entries){Properties p=new Properties();for(int i=0;i<entries.length;i+=2)p.setProperty(entries[i],entries[i+1]);return new Equipment(p);}
 static Game game(Equipment e){Game g=new Game(7,new Economy(new Economy.MemoryStore()),e);g.start();g.contacts.clear();return g;}
 static Game.Missile flight(){Game.Missile m=new Game.Missile();m.z=3;m.speed=.2;m.vx=1;return m;}
 static void step(Game.Missile m,Equipment.Weapon w,boolean turn,double dt){m.age+=dt;MissileMotion.step(m,w,turn?0:100,turn?100:0,3,true,dt);}
 static void bad(String... entries){try{config(entries);throw new AssertionError("Invalid config accepted");}catch(IllegalArgumentException expected){}}
 public static void main(String[] args)throws Exception{
  Equipment defaults=Equipment.defaults(),asset;File assetFile=new File("assets/equipment.properties");if(!assetFile.exists())assetFile=new File("radar/assets/equipment.properties");try(InputStream in=new FileInputStream(assetFile)){asset=Equipment.load(in);}check(asset.all.length==9&&asset.radar.name.equals(defaults.radar.name),"asset loads");for(int i=0;i<asset.all.length;i++){check(asset.all[i].id.equals(defaults.all[i].id)&&asset.all[i].name.equals(defaults.all[i].name)&&asset.all[i].massKg==defaults.all[i].massKg&&asset.all[i].thrustN==defaults.all[i].thrustN&&asset.all[i].guidance==defaults.all[i].guidance&&asset.all[i].radarMode==defaults.all[i].radarMode&&asset.all[i].rangeKm==defaults.all[i].rangeKm&&asset.all[i].guidanceSeconds==defaults.all[i].guidanceSeconds&&asset.all[i].seekerKm==defaults.all[i].seekerKm&&asset.all[i].seekerFovDeg==defaults.all[i].seekerFovDeg&&asset.all[i].maxSpeedKmh==defaults.all[i].maxSpeedKmh&&asset.all[i].supportRecoverySeconds==defaults.all[i].supportRecoverySeconds,"asset matches fallback");}check(asset.radar.illuminationChannels==defaults.radar.illuminationChannels&&asset.radar.midcourseChannels==defaults.radar.midcourseChannels&&asset.radar.acquireObservations==defaults.radar.acquireObservations&&asset.radar.detectionAbsoluteKm==defaults.radar.detectionAbsoluteKm,"sensor asset matches fallback");Equipment fractional=config("missile.rampart.maneuverability","4.25");check(Math.abs(fractional.primary.maneuverability-4.25)<1e-9&&Math.abs(fractional.primary.maneuverG-10.5)<1e-9,"fractional maneuverability maps independently into configured turning G");Equipment support=config("radar.tracks","2","radar.channels","4");check(support.radar.channels==4&&support.radar.tracks==2,"shared per-missile channel capacity is independent of contact slots");Equipment independent=config("radar.illuminationChannels","1","radar.midcourseChannels","4");check(independent.radar.illuminationChannels==1&&independent.radar.midcourseChannels==4,"channel pools independently configurable");
  bad("radar.scanSpeed","6.01");bad("radar.switchSeconds","-1");bad("radar.lockAcquireSeconds","-1");bad("radar.lockLossSeconds","-1");bad("radar.irstUpdateSeconds","0");bad("radar.irstCapacity","0");bad("radar.launcherCapacity","0");bad("radar.reserveRounds","-1");bad("radar.reloadSeconds","0");bad("radar.sweepFastSeconds","11");bad("radar.trackTimeoutSeconds","5");bad("radar.contactTimeoutSeconds","20");bad("missile.rampart.maneuverability","0.99");bad("missile.rampart.maneuverability","10.01");bad("missile.rampart.fuzeKm","0.001");bad("missile.rampart.warheadKg","-1");bad("missile.rampart.warheadType","BAD");bad("radar.detectionAbsoluteKm","29");bad("radar.trackingAbsoluteKm","23");bad("radar.lockAbsoluteKm","15");bad("radar.trackingAbsoluteKm","37");bad("radar.lockAbsoluteKm","31");bad("missile.active.seekerFovDeg","4");bad("missile.active.seekerFovDeg","181");bad("radar.illuminationChannels","-1");bad("radar.midcourseChannels","-1");bad("radar.illuminationChannels","6");bad("radar.midcourseChannels","73");bad("radar.supportedMissiles","0");bad("radar.acquireObservations","1");bad("radar.lockQualityMinimum","0.1");bad("radar.tracks","0");bad("radar.tracks","1.5");bad("radar.scanSpeed","11");bad("radar.infrared","maybe");bad("radar.trackingKm","41");bad("radar.lockKm","33");bad("missile.rampart.massKg","0");bad("missile.rampart.maxG","NaN");bad("missile.rampart.thrustN","Infinity");bad("missile.rampart.radarMode","NONE");bad("missile.ir6.radarMode","ACTIVE");bad("missile.rampart.guidance","BOGUS");bad("radar.trakcs","7");bad("missile.rampart.burnSeconds","66");
  Game g=game(config("radar.detectionKm","20","radar.trackingKm","12","radar.lockKm","8","radar.detectionAbsoluteKm","20","radar.trackingAbsoluteKm","12","radar.lockAbsoluteKm","8","radar.tracks","1","radar.channels","1"));Game.Contact t=GameTest.target(g,0);t.x=t.px=21;check(g.signal(t)==0,"detection range");t.x=t.px=15;t.radarTracked=false;check(g.signal(t)>0&&g.visible(t)&&!g.liveTrack(t)&&g.track(t).contains("RANGE"),"detected outside tracking envelope");t.x=t.px=10;g.track(t);for(int i=0;i<2;i++){g.elapsed+=1;g.observe(t);}check(g.liveTrack(t)&&g.lockBlock(t).contains("RANGE"),"tracking outside locking envelope");t.x=t.px=6;GameTest.lock(g,t);check(t.illuminated,"inside lock range");Game.Contact other=GameTest.target(g,1);other.radarTracked=false;check(g.track(other).contains("NO FREE TRACK SLOT")&&!other.radarTracked,"track capacity enforced");t.alive=false;g.maintainTracks();g.track(other);check(g.trackedCount()==1&&other.radarTracked,"track slot released");other.x=13;g.elapsed+=1;g.observe(other);g.maintainTracks();check(!other.radarTracked,"out of tracking range releases slot");
  g=game(config("radar.channels","1"));t=GameTest.target(g,0);other=GameTest.target(g,1);GameTest.lock(g,t);check(g.lockBlock(other)==null,"hard locks alone do not occupy shared missile guidance capacity");g.battery.parts[Battery.RADAR].hp=25;g.syncBattery();g.maintainTracks();check(g.channels()==0&&Math.abs(g.trackingRange()-12)<1e-9&&Math.abs(g.lockRange()-8)<1e-9,"physical radar damage reduces tracking and lock envelopes");
  Game fast=game(config("radar.scanSpeed","6")),slow=game(config("radar.scanSpeed","1"));fast.tick(.05);slow.tick(.05);check(Math.abs(fast.sweep/slow.sweep-2)<1e-8,"configured scan speed");
  g=game(config("radar.infrared","false"));t=GameTest.target(g,0);g.toggleWeapon();check(!g.irMode&&g.ir.begin(t).equals("EQUIP AN IR MISSILE"),"IR requires owned equipped weapon");Economy irWallet=new Economy(new Economy.MemoryStore());irWallet.equip("ir6");g=new Game(7,irWallet,config("radar.infrared","false"));g.start();g.contacts.clear();t=InfraredTest.target(g);check(g.ir.canSee(t)&&g.ir.beginBlock(t)==null&&g.ir.observeIrst(t)==null,"missile seeker uses radar cue without an IRST");
  Game.Missile a=flight(),b=flight();step(a,defaults.primary,false,1);step(b,config("missile.rampart.massKg","1160").primary,false,1);check(a.speed>b.speed&&a.x>b.x,"mass changes acceleration and distance");a=flight();b=flight();step(a,defaults.primary,false,1);step(b,config("missile.rampart.thrustN","9000").primary,false,1);check(a.speed>b.speed,"thrust changes acceleration");
  a=flight();Equipment.Weapon capped=config("missile.rampart.maxSpeedKmh","720").primary;for(int i=0;i<60;i++)step(a,capped,false,.1);check(a.speed<=.2,"maximum speed cap");double boosted=a.speed;for(int i=0;i<60;i++)step(a,capped,false,.1);check(a.speed<boosted,"coasting loses energy");
  a=flight();b=flight();step(a,defaults.primary,true,.1);step(b,config("missile.rampart.maneuverability","1").primary,true,.1);check(a.vy>b.vy,"maneuverability rating controls configured turn limit");a=flight();b=flight();step(a,defaults.primary,true,.1);step(b,config("missile.rampart.maxAoADeg","1").primary,true,.1);check(a.vy>b.vy,"AOA limits turns");a=flight();b=flight();step(a,defaults.primary,true,.1);step(b,defaults.primary,false,.1);check(a.speed<b.speed,"turn energy cost");
  g=game(config("missile.rampart.guidanceSeconds","1","missile.rampart.burnSeconds","1"));t=GameTest.target(g,0);GameTest.lock(g,t);g.launch(t);a=g.missiles.get(0);a.age=1.1;check(!g.guided(a),"guidance time expires while locked");for(int i=0;i<42&&a.alive;i++)g.fly(a,.1);check(!a.alive&&g.kills==0,"unguided missile expires without phantom hit");
  g=game(config("missile.rampart.radarMode","ACTIVE","missile.rampart.seekerKm","5"));t=GameTest.target(g,0);GameTest.lock(g,t);g.launch(t);a=g.missiles.get(0);check(g.guided(a)&&!a.autonomous,"active midcourse uses link");g.release(t);check(g.guided(a),"active uses TWS after hard lock release");t.radarTracked=false;check(!g.guided(a),"active requires track before acquisition");t.radarTracked=true;a.x=5;a.z=3;g.guided(a);for(int i=0;i<20&&!a.autonomous;i++)g.fly(a,.025);check(g.guided(a)&&a.autonomous&&g.channels()==0,"active seeker takes over after acquisition and frees channel");t.radarTracked=false;check(g.guided(a),"active guidance independent after acquisition");
  check(defaults.enemy[2].guidance==Equipment.Guidance.COMMAND&&defaults.enemy[3].radarMode==Equipment.RadarMode.PASSIVE&&defaults.enemy[4].radarMode==Equipment.RadarMode.PASSIVE,"legacy enemy command and passive profiles preserved");
  g=game(config("missile.kh58.thrustN","0","missile.kh58.maxSpeedKmh","720"));Game.EnemyMissile e=InterceptionTest.incoming(g,4);g.flyEnemy(e,.1);check(e.speed<.18,"enemy shares configured motion");g=game(config("missile.kh58.guidanceSeconds","1","missile.kh58.burnSeconds","1"));e=InterceptionTest.incoming(g,4);for(int i=0;i<42&&e.alive;i++)g.flyEnemy(e,.1);check(!e.alive&&g.radarHits==0,"enemy guidance time enforced");
  irWallet=new Economy(new Economy.MemoryStore());irWallet.equip("ir6");g=new Game(7,irWallet,config("radar.infrared","true","radar.irLockKm","9","missile.ir6.guidanceSeconds","1","missile.ir6.burnSeconds","1"));g.start();g.contacts.clear();t=InfraredTest.target(g);g.weaponLock(t);InfraredTest.warm(g);g.fireWeapon(t);a=g.missiles.get(0);for(int i=0;i<82&&a.alive;i++)g.fly(a,.1);check(!a.alive&&g.kills==0,"IR guidance time enforced");
  System.out.println("PASS: profile loading/validation, radar envelopes/capacity/channels/scan speed, IR compatibility, mass/thrust/speed/G/AOA/energy, all guidance modes and friendly/enemy/IR timeouts");
 }
}
