package com.jb.radar;
import java.util.*;import java.io.*;
public class EquipmentTest {
 static void check(boolean b,String m){if(!b)throw new AssertionError(m);}
 static Equipment config(String... entries){Properties p=new Properties();for(int i=0;i<entries.length;i+=2)p.setProperty(entries[i],entries[i+1]);return new Equipment(p);}
 static Game game(Equipment e){Game g=new Game(7,new Economy(new Economy.MemoryStore()),e);g.start();g.contacts.clear();return g;}
 static Game.Missile flight(){Game.Missile m=new Game.Missile();m.z=3;m.speed=.2;m.vx=1;return m;}
 static void step(Game.Missile m,Equipment.Weapon w,boolean turn,double dt){m.age+=dt;MissileMotion.step(m,w,turn?0:100,turn?100:0,3,true,dt);}
 static void bad(String... entries){try{config(entries);throw new AssertionError("Invalid config accepted");}catch(IllegalArgumentException expected){}}
 public static void main(String[] args)throws Exception{
  Equipment defaults=Equipment.defaults(),asset;File assetFile=new File("assets/equipment.properties");if(!assetFile.exists())assetFile=new File("radar/assets/equipment.properties");try(InputStream in=new FileInputStream(assetFile)){asset=Equipment.load(in);}check(asset.all.length==7&&asset.radar.name.equals(defaults.radar.name),"asset loads");for(int i=0;i<7;i++){check(asset.all[i].massKg==defaults.all[i].massKg&&asset.all[i].thrustN==defaults.all[i].thrustN&&asset.all[i].guidance==defaults.all[i].guidance&&asset.all[i].radarMode==defaults.all[i].radarMode,"asset matches fallback");}
  bad("radar.tracks","0");bad("radar.tracks","1.5");bad("radar.scanSpeed","11");bad("radar.infrared","maybe");bad("radar.trackingKm","41");bad("radar.lockKm","33");bad("missile.hawk.massKg","0");bad("missile.hawk.maxG","NaN");bad("missile.hawk.thrustN","Infinity");bad("missile.hawk.radarMode","NONE");bad("missile.ir6.radarMode","ACTIVE");bad("missile.hawk.guidance","BOGUS");bad("radar.trakcs","7");bad("missile.hawk.burnSeconds","66");
  Game g=game(config("radar.detectionKm","20","radar.trackingKm","12","radar.lockKm","8","radar.tracks","1","radar.channels","1"));Game.Contact t=GameTest.target(g,0);t.x=t.px=21;check(g.signal(t)==0,"detection range");t.x=t.px=15;t.radarTracked=false;check(g.signal(t)>0&&g.visible(t)&&!g.liveTrack(t)&&g.track(t).contains("RANGE"),"detected outside tracking envelope");t.x=t.px=10;g.track(t);check(g.liveTrack(t)&&g.lockBlock(t).contains("RANGE"),"tracking outside locking envelope");t.x=t.px=6;g.illuminate(t);check(t.illuminated,"inside lock range");Game.Contact other=GameTest.target(g,1);other.radarTracked=false;check(g.track(other).contains("MAXIMUM")&&!other.radarTracked,"track capacity enforced");t.alive=false;g.maintainTracks();g.track(other);check(g.trackedCount()==1&&other.radarTracked,"track slot released");other.x=other.px=13;g.maintainTracks();check(!other.radarTracked,"out of tracking range releases slot");
  g=game(config("radar.channels","1"));t=GameTest.target(g,0);other=GameTest.target(g,1);g.illuminate(t);check(g.lockBlock(other).contains("CHANNELS"),"configured channels");g.maxRange=5;g.maintainTracks();check(g.channels()==0&&g.trackingRange()==5&&g.lockRange()==5,"damage caps all radar ranges");
  Game fast=game(config("radar.scanSpeed","10")),slow=game(config("radar.scanSpeed","1"));fast.tick(.05);slow.tick(.05);check(Math.abs(fast.sweep/slow.sweep-10)<1e-8,"configured scan speed");
  g=game(config("radar.infrared","false"));t=GameTest.target(g,0);g.toggleWeapon();check(!g.irMode&&g.ir.begin(t).contains("DOES NOT SUPPORT"),"IR compatibility");g=game(config("radar.irLockKm","3"));t=InfraredTest.target(g);check(!g.ir.canSee(t),"platform IR lock range");
  Game.Missile a=flight(),b=flight();step(a,defaults.primary,false,1);step(b,config("missile.hawk.massKg","1160").primary,false,1);check(a.speed>b.speed&&a.x>b.x,"mass changes acceleration and distance");a=flight();b=flight();step(a,defaults.primary,false,1);step(b,config("missile.hawk.thrustN","42000").primary,false,1);check(a.speed>b.speed,"thrust changes acceleration");
  a=flight();Equipment.Weapon capped=config("missile.hawk.maxSpeedKmh","720").primary;for(int i=0;i<60;i++)step(a,capped,false,.1);check(a.speed<=.2,"maximum speed cap");double boosted=a.speed;for(int i=0;i<60;i++)step(a,capped,false,.1);check(a.speed<boosted,"coasting loses energy");
  a=flight();b=flight();step(a,defaults.primary,true,.1);step(b,config("missile.hawk.maxG","1").primary,true,.1);check(a.vy>b.vy,"G load limits turns");a=flight();b=flight();step(a,defaults.primary,true,.1);step(b,config("missile.hawk.maxAoADeg","1").primary,true,.1);check(a.vy>b.vy,"AOA limits turns");a=flight();b=flight();step(a,defaults.primary,true,.1);step(b,defaults.primary,false,.1);check(a.speed<b.speed,"turn energy cost");
  g=game(config("missile.hawk.guidanceSeconds","1","missile.hawk.burnSeconds","1"));t=GameTest.target(g,0);g.illuminate(t);g.launch(t);a=g.missiles.get(0);a.age=1.1;check(!g.guided(a),"guidance time expires while locked");for(int i=0;i<42&&a.alive;i++)g.fly(a,.1);check(!a.alive&&g.kills==0,"unguided missile expires without phantom hit");
  g=game(config("missile.hawk.radarMode","ACTIVE","missile.hawk.seekerKm","5"));t=GameTest.target(g,0);g.illuminate(t);g.launch(t);a=g.missiles.get(0);check(g.guided(a)&&!a.autonomous,"active midcourse uses link");g.release(t);check(!g.guided(a),"active needs link before acquisition");g.illuminate(t);a.x=5;a.z=3;check(g.guided(a)&&a.autonomous&&g.channels()==0,"active seeker takes over and frees channel");g.release(t);t.radarTracked=false;check(g.guided(a),"active guidance independent after acquisition");
  g=game(config("missile.hawk.guidance","COMMAND","missile.hawk.radarMode","NONE"));t=GameTest.target(g,0);g.illuminate(t);g.launch(t);a=g.missiles.get(0);check(g.guided(a),"command link guides");g.release(t);check(!g.guided(a),"command link loss");
  g=game(config("missile.hawk.radarMode","PASSIVE","radar.channels","0"));t=GameTest.target(g,0);check(g.lockBlock(t).contains("EMISSION"),"passive needs emitter");t.radarEmitting=true;g.illuminate(t);g.launch(t);a=g.missiles.get(0);g.release(t);check(g.guided(a)&&g.channels()==0,"passive independent emission homing");t.radarEmitting=false;check(!g.guided(a),"passive loses silent target");
  g=game(config("missile.kh58.thrustN","0","missile.kh58.maxSpeedKmh","720"));Game.EnemyMissile e=InterceptionTest.incoming(g,4);g.flyEnemy(e,.1);check(e.speed<.18,"enemy shares configured motion");g=game(config("missile.kh58.guidanceSeconds","1","missile.kh58.burnSeconds","1"));e=InterceptionTest.incoming(g,4);for(int i=0;i<42&&e.alive;i++)g.flyEnemy(e,.1);check(!e.alive&&g.radarHits==0,"enemy guidance time enforced");
  g=game(config("missile.ir6.guidanceSeconds","1","missile.ir6.burnSeconds","1"));t=InfraredTest.target(g);g.toggleWeapon();g.weaponLock(t);InfraredTest.warm(g);g.fireWeapon(t);a=g.missiles.get(0);for(int i=0;i<32&&a.alive;i++)g.fly(a,.1);check(!a.alive&&g.kills==0,"IR guidance time enforced");
  System.out.println("PASS: profile loading/validation, radar envelopes/capacity/channels/scan speed, IR compatibility, mass/thrust/speed/G/AOA/energy, all guidance modes and friendly/enemy/IR timeouts");
 }
}
