package com.jb.radar;
import java.util.*;
/** v0.19 guide behavior independent of the excluded beta equipment and aircraft roster. */
public class GuideMechanicsTest {
 static void check(boolean v,String m){if(!v)throw new AssertionError(m);}
 static class Certain extends Random {private static final long serialVersionUID=1;public double nextDouble(){return 0;}public double nextGaussian(){return 0;}}
 static Game game(String... kv){Properties p=new Properties();for(int i=0;i<kv.length;i+=2)p.setProperty(kv[i],kv[i+1]);Game g=new Game(18,new Economy(new Economy.MemoryStore()),new Equipment(p));g.start();g.contacts.clear();g.enemyMissiles.clear();g.random=new Certain();return g;}
 static Game.Contact ready(Game g,int id,double x){Game.Contact t=new Game.Contact();t.id=id;t.x=t.px=t.detectionX=x;t.alt=t.palt=3000;t.seen=t.detectedAt=g.elapsed;t.samples=t.detectionSamples=4;t.quality=t.detectionQuality=1;t.radarTracked=t.hadTrack=true;g.contacts.add(t);return t;}
 static void lock(Game g,Game.Contact t){check(g.lockBlock(t)==null,"lock permitted: "+g.lockBlock(t));g.illuminate(t);g.elapsed+=g.equipment.radar.lockAcquireSeconds+.001;g.maintainTracks();check(g.hardLocked(t),"timed lock established");}
 static Game.Missile fire(Game g,Game.Contact t){int n=g.missiles.size();check(g.launchBlock(t)==null,"launch eligible: "+g.launchBlock(t));g.launch(t);check(g.missiles.size()==n+1,"launch created projectile");return g.missiles.get(n);}
 static void sensorControls(){Game g=game();check(g.launchers.length==4&&g.ready()==12&&g.reserve==12,"four real launchers and configured inventory");Game.Contact t=ready(g,1,10);lock(g,t);Game.Missile m=fire(g,t);int rounds=g.ready(),world=g.contacts.size();g.toggleAutoTrack();double oldSeen=t.seen,oldX=t.px;g.elapsed+=1;t.x=8;g.observe(t);check(t.seen==oldSeen&&t.px==oldX&&t.detectionX==8&&g.trackStage(t)==Game.TrackStage.COASTING,"AUTO OFF freezes track but search refreshes plot");Game.Contact plot=new Game.Contact();plot.id=2;plot.x=9;plot.alt=5000;g.contacts.add(plot);g.observe(plot);check(g.visible(plot)&&!g.tracked(plot)&&plot.samples==0&&g.altitudeText(plot).equals("---"),"AUTO OFF new contact detected without detail");g.elapsed=26;t.x=7;g.observe(t);g.maintainTracks();check(!g.tracked(t)&&g.visible(t)&&g.displayX(t)==7,"track expires while search detection persists");g.toggleRadar();check(g.radarReady(),"radar switching delay keeps current state");g.elapsed+=g.equipment.radar.switchSeconds+.01;g.sensorTick();check(!g.radarReady()&&!g.hardLocked(t),"radar off stops illumination");double detection=t.detectedAt;g.elapsed+=1;g.observe(t);check(t.detectedAt==detection,"radar off cannot measure");g.resetRadar();check(g.contacts.size()==world+1&&g.missiles.contains(m)&&m.alive&&g.ready()==rounds,"RESET keeps world, missiles and inventory");check(!g.detected(t)&&t.samples==0&&!t.radarTracked,"RESET clears only radar records");g.toggleRadar();g.elapsed+=g.equipment.radar.switchSeconds+.01;g.sensorTick();check(g.radarReady(),"radar returns after delay");g.toggleAutoTrack();g.observe(t);check(t.samples==1&&g.trackStage(t)==Game.TrackStage.ACQUIRING,"reset reacquisition begins with first tracked observation");}
 static void detectionVersusTracking(){Game g=game("radar.tracks","2","radar.channels","2");for(int i=0;i<6;i++){Game.Contact t=new Game.Contact();t.id=i+1;t.x=10+i;t.alt=3000;g.contacts.add(t);g.observe(t);}check(g.trackedCount()==2,"six plots only two slots");Game.Contact first=g.contacts.get(0),last=g.contacts.get(5);for(Game.Contact t:g.contacts)check(g.detected(t),"all six detections persist");g.elapsed=5;for(Game.Contact t:g.contacts){t.x-=.5;g.observe(t);}check(g.stableTrack(first)&&last.samples==0&&last.palt==0&&last.pspeed==0&&last.recognizedType.isEmpty(),"untracked detections never accumulate detail or NCTR");Game.Contact nearby=new Game.Contact();nearby.id=7;nearby.x=3;nearby.alt=3000;g.contacts.add(nearby);g.elapsed=6;g.observe(nearby);check(!g.tracked(nearby)&&g.tracked(first),"default retains existing tracks against closer aircraft");g.prioritize(last);check(g.tracked(last)&&last.samples==0&&g.speedText(last).equals("---"),"new prioritized slot starts acquisition without hidden history");g.elapsed=10;g.observe(last);check(last.samples==1&&!g.stableTrack(last),"first assigned revisit has no velocity");g.elapsed=15;last.x-=1;g.observe(last);check(g.stableTrack(last)&&Math.abs(last.pspeed-720)<.01,"second assigned revisit estimates motion");double seen=last.seen;g.cueRadar(last);check(last.seen==seen&&last.radarCuePending,"cue cannot fabricate an extra measurement");}
 static void lockLifecycle(){Game g=game();Game.Contact t=ready(g,1,9);g.illuminate(t);check(g.lockAcquiring(t)&&!g.hardLocked(t)&&g.channels()==0,"locking is timed and uses no missile channel");g.elapsed=g.equipment.radar.lockAcquireSeconds-.01;g.maintainTracks();check(!g.hardLocked(t),"acquisition cannot complete early");g.elapsed+=.02;g.maintainTracks();check(g.hardLocked(t),"acquisition completion");t.missed=1;t.missedAt=g.elapsed;g.maintainTracks();check(g.hardLocked(t),"brief missed track update tolerated");g.elapsed+=g.equipment.radar.lockLossSeconds+.01;g.maintainTracks();check(!g.hardLocked(t),"lock tolerance expires");}
 static void channelsAndSearch(){Game g=game();Game.Contact t=ready(g,1,9);lock(g,t);Game.Missile first=fire(g,t),second=fire(g,t);check(g.channels()==2,"same-target SARH missiles use separate shared channels");int rounds=g.ready();String warning=g.launch(t);check(warning.contains("TRANSFER")&&g.ready()==rounds&&first.linkReserved,"overflow requires explicit second step");g.launch(t,true);check(g.ready()==rounds-1&&!first.linkReserved&&first.supportReleased&&second.linkReserved&&g.channels()==2,"confirmed overflow displaces oldest missile only");check(!g.guided(first)&&g.hardLocked(t),"displaced SARH loses support even though target still illuminated");g=game();g.weapon=g.equipment.active;t=ready(g,1,20);first=fire(g,t);second=fire(g,t);g.launch(t,true);check(first.seekerState==Game.SeekerState.SEARCHING&&!first.linkReserved&&g.channels()==2,"displaced active enters early search and frees channel");second.x=16;second.z=3;MissileMotion.aim(second,1,0,0);g.guided(second);check(second.seekerState==Game.SeekerState.SEARCHING&&!second.autonomous&&!second.linkReserved&&g.channels()==1,"normal seeker activation frees channel before acquisition");for(int i=0;i<10&&!second.autonomous;i++)g.fly(second,.05);check(second.autonomous&&g.missileState(second).equals("SEEKER LOCK"),"seeker uses acquisition time");Game.Missile third=g.missiles.get(2);t.radarTracked=false;g.fly(third,.05);check(third.seekerState==Game.SeekerState.SEARCHING&&!third.linkReserved,"external update loss triggers early seeker search");}
 static void retargeting(){Game g=game("missile.rampart.retargeting","true");Game.Contact old=ready(g,1,6),next=ready(g,2,7);lock(g,old);Game.Missile m=fire(g,old);g.nextTarget(old);check(m.target==old,"selection alone never retargets");g.release(old);lock(g,next);check(m.target==next&&g.guided(m),"quick new illumination lock retargets within FOV and window");g=game("missile.rampart.retargeting","true");old=ready(g,1,6);next=ready(g,2,-7);lock(g,old);m=fire(g,old);g.release(old);lock(g,next);check(m.target==old,"new lock outside missile FOV does not redirect");}
 static void identificationAndScale(){Game a=game(),b=game();a.range=10;b.range=30;Game.Contact x=new Game.Contact(),y=new Game.Contact();x.id=y.id=1;x.x=y.x=14;x.alt=y.alt=3000;a.contacts.add(x);b.contacts.add(y);a.observe(x);b.observe(y);check(a.detected(x)&&x.px==y.px&&x.quality==y.quality,"view scale cannot alter detection or measurement quality");x.recognizedType="Su-25";check(a.allegiance(x)==Game.Allegiance.UNKNOWN&&a.identity(x)==0,"type recognition cannot prove hostility");a.identifyAllegiance(x,Game.Allegiance.FRIENDLY,"IFF");check(a.identity(x)==3,"explicit friendly evidence preserved");Game.EnemyMissile missile=new Game.EnemyMissile();missile.id=101;missile.weapon=4;missile.samples=9;missile.confidence=1;check(a.tag(missile).equals("T-101")&&a.missileName(missile).equals("UNKNOWN MSL"),"hidden missile class never leaks as sensor recognition");check(!a.nctrCovers("Kh-58U",true)&&a.nctrCovers("Su-25",false),"recognition database coverage enforced");}
 static void damage(){Game g=game();Game.Contact t=ready(g,1,8);Game.Missile m=new Game.Missile();m.target=t;m.profile=g.weapon;m.speed=.6;m.vx=1;double direct=g.hitDamage(m,t,0),near=g.hitDamage(m,t,.09),far=g.hitDamage(m,t,.19);check(direct>100&&near>0&&near<100&&far<near,"explosive distance curve permits partial hits");t.vulnerability=.5;check(Math.abs(g.hitDamage(m,t,0)-direct*.5)<1e-8,"configured target vulnerability scales damage");t.vulnerability=1;g.resolvePlayerHit(m,.09,false);check(t.alive&&t.health>0&&t.health<100&&!m.alive,"near detonation applies partial persistent health loss");g=game("missile.rampart.warheadKg","5");t=ready(g,1,8);m=new Game.Missile();m.profile=g.weapon;m.target=t;check(Math.abs(g.hitDamage(m,t,0)-5*g.weapon.damageScale)<1e-8,"configured explosive content controls damage: "+g.hitDamage(m,t,0));g=game("missile.rampart.warheadType","KINETIC","missile.rampart.warheadKg","0");t=ready(g,1,8);m=new Game.Missile();m.profile=g.weapon;m.target=t;m.speed=.6;m.vx=1;check(g.hitDamage(m,t,.03)==0&&!g.canDetonate(m,.03,true),"kinetic near miss produces no blast");check(g.hitDamage(m,t,.02)>100&&g.canDetonate(m,.02,false),"kinetic direct impact uses mass and speed");}
 static void radarOffEnemyAttack(){Game g=game();Game.Contact t=ready(g,1,7);t.weapon=0;t.heading=-Math.PI/2;t.born=-40;g.radarOn=false;g.tryEnemyLaunch(t);check(g.enemyMissiles.size()==1,"radar OFF cannot disable enemy laser-guided attack");Game.EnemyMissile m=g.enemyMissiles.get(0);g.flyEnemy(m,.1);check(m.lost==0,"laser missile own-source LOS persists with player radar OFF");}
 public static void main(String[] args){sensorControls();detectionVersusTracking();lockLifecycle();channelsAndSearch();retargeting();identificationAndScale();damage();radarOffEnemyAttack();System.out.println("PASS: sensor controls/reset, detection-only isolation, track retention, timed locks, confirmed overflow, early seeker, SARH retarget, independent identification, view scale, damage curves and radar-off enemy fairness");}
}
