package com.jb.radar;
public class InfraredTest {
 static void check(boolean b,String s){if(!b)throw new AssertionError(s);}
 static Game make(){Game g=new Game(37);g.start();g.contacts.clear();return g;}
 static Game.Contact target(Game g){Game.Contact t=GameTest.target(g,0);t.x=t.px=4;t.y=t.py=0;t.alt=t.palt=1800;t.heading=Math.PI/2;t.flareBursts=0;t.nextFlare=9999;return t;}
 static void warm(Game g){for(int i=0;i<70;i++){g.elapsed+=.05;g.ir.tick(.05);}}
 public static void main(String[] args){Game g=make();Game.Contact t=target(g);g.toggleWeapon();g.weaponLock(t);check(!g.ir.locked&&g.weaponBlock(t)!=null,"no instant lock or launch");double evasion=t.evasion;warm(g);check(g.ir.locked&&g.channels()==0&&t.evasion==evasion,"passive acquisition uses no channel or warning");check(g.weaponBlock(t)==null,"fire enabled after acquisition");g.fireWeapon(t);Game.Missile m=g.missiles.get(0);check(m.infrared&&g.ir.ammo==5&&g.ready()==9&&g.reserve==9,"separate IR inventory");g.weaponRelease(t);g.toggleWeapon();g.maxRange=1;t.seen=-100;for(int i=0;i<1500&&m.alive;i++){g.elapsed+=.02;g.fly(m,.02);}check(g.kills==1&&!t.alive,"self guidance after release, mode switch and radar track loss");
 g=make();t=target(g);t.x=t.px=7;t.alt=t.palt=1000;t.heading=Math.PI/2;check(g.ir.canSee(t),"rear aspect stronger");t.heading=-Math.PI/2;check(!g.ir.canSee(t),"head on weaker at same range");t.x=13;t.y=-15;t.alt=100;check(g.ir.heat(t,0,0,.115)==0,"terrain masks heat");t.x=2;t.y=0;t.alt=7000;check(!g.ir.canSee(t),"ceiling gate");
 g=make();t=target(g);g.toggleWeapon();g.weaponLock(t);warm(g);t.flareBursts=1;g.ir.deployFlares(t);g.ir.tick(.1);check(!g.ir.locked&&g.weaponBlock(t)!=null,"flares interrupt acquisition");for(int i=0;i<120;i++)g.ir.tick(.05);check(g.ir.locked,"reacquire after flare expires");g.fireWeapon(t);m=g.missiles.get(0);t.flareBursts=1;g.ir.deployFlares(t);g.fly(m,.05);check(m.decoy!=null,"in cone hot flare diverts IR");for(int i=0;i<1800&&m.alive;i++){g.elapsed+=.02;g.ir.tick(.02);g.fly(m,.02);}check(t.alive&&g.kills==0&&g.misses==1,"flare miss cannot kill aircraft");
 g=make();t=target(g);g.toggleWeapon();for(int shot=0;shot<6;shot++){g.weaponLock(t);warm(g);g.fireWeapon(t);}check(g.ir.ammo==0&&g.ir.reserve==6&&g.ir.reload==60,"empty IR starts full reload");double wait=g.ir.reload;g.running=false;g.tick(.1);check(g.ir.reload==wait,"pause freezes reload");for(int i=0;i<599;i++)g.ir.tick(.1);check(g.ir.ammo==0,"not early reload");g.ir.tick(.11);check(g.ir.ammo==6&&g.ir.reserve==0,"reload conserves ammo");check(g.ir.ammo+g.ir.reserve+g.ir.shots==12,"IR conservation");g.start();check(!g.irMode&&!g.ir.active&&g.ir.ammo==6&&g.ir.reserve==6&&g.ir.flares.isEmpty(),"IR reset");
 g=make();t=target(g);g.toggleWeapon();g.weaponLock(t);warm(g);g.fireWeapon(t);m=g.missiles.get(0);t.x=-4;for(int i=0;i<50&&m.alive;i++)g.fly(m,.05);check(!m.alive&&t.alive&&g.misses==1,"seeker cannot track outside cone");
 g=make();Game.EnemyMissile e=new Game.EnemyMissile();e.id=101;e.weapon=4;e.x=e.px=4;e.alt=e.palt=1800;e.z=1.8;e.priority=true;e.samples=3;e.seen=0;g.enemyMissiles.add(e);g.toggleWeapon();g.weaponLock(e);warm(g);g.fireWeapon(e);m=g.missiles.get(0);for(int i=0;i<1200&&m.alive;i++){g.elapsed+=.02;g.fly(m,.02);if(e.alive)g.flyEnemy(e,.02);}check(g.kills==1&&g.radarHits==0,"IR intercepts hot incoming missile");
 g=make();t=target(g);g.toggleWeapon();g.weaponLock(t);warm(g);for(int i=0;i<600;i++)g.ir.tick(.05);check(!g.ir.active,"seeker timeout");System.out.println("PASS: IR acquisition, passive lock, aspect, terrain, ceiling, independent flight, flare distraction, reload, pause, timeout and reset");}
}
