package com.jb.radar;
public class InfraredTest {
 static void check(boolean b,String s){if(!b)throw new AssertionError(s);}
 static Game make(){java.util.Properties p=new java.util.Properties();p.setProperty("radar.infrared","true");p.setProperty("radar.irLockKm","9");Economy e=new Economy(new Economy.MemoryStore());e.equip("ir6");Game g=new Game(37,e,new Equipment(p));g.start();g.contacts.clear();return g;}
 static Game.Contact target(Game g){Game.Contact t=GameTest.target(g,0);t.x=t.px=4;t.y=t.py=0;t.alt=t.palt=1800;t.heading=Math.PI/2;t.flareBursts=0;t.nextFlare=9999;return t;}
 static void warm(Game g){for(int i=0;i<70;i++){g.elapsed+=.05;g.ir.tick(.05);}}
 public static void main(String[] args){Game g=make();Game.Contact t=target(g);g.weaponLock(t);check(!g.ir.locked&&g.weaponBlock(t)!=null,"no instant lock or launch");double evasion=t.evasion;warm(g);check(g.ir.locked&&g.channels()==0&&t.evasion==evasion,"passive acquisition uses no channel or warning");check(g.weaponBlock(t)==null,"fire enabled after acquisition");g.fireWeapon(t);Game.Missile m=g.missiles.get(0);check(m.infrared&&g.ready()==8&&g.reserve==9&&g.midcourseUsed()==0&&g.illuminationUsed()==0,"IR consumes shared launcher inventory without guidance channels");g.weaponRelease(t);g.maxRange=1;t.seen=-100;for(int i=0;i<1500&&m.alive;i++){g.elapsed+=.02;g.fly(m,.02);}check(g.kills==1&&!t.alive,"self guidance after seeker release and radar track loss");
 g=make();t=target(g);t.x=t.px=7;t.alt=t.palt=1000;t.heading=Math.PI/2;check(g.ir.canSee(t),"rear aspect stronger");t.heading=-Math.PI/2;check(!g.ir.canSee(t),"head on weaker at same range");t.x=13;t.y=-15;t.alt=100;check(g.ir.heat(t,0,0,.115)==0,"terrain masks heat");t.x=2;t.y=0;t.alt=7000;check(!g.ir.canSee(t),"ceiling gate");
 g=make();t=target(g);g.weaponLock(t);warm(g);t.flareBursts=1;g.ir.deployFlares(t);g.ir.tick(.1);check(!g.ir.locked&&g.weaponBlock(t)!=null,"flares interrupt acquisition");for(int i=0;i<120;i++)g.ir.tick(.05);check(g.ir.locked,"reacquire after flare expires");g.fireWeapon(t);m=g.missiles.get(0);t.flareBursts=1;g.ir.deployFlares(t);g.fly(m,.05);check(m.decoy!=null&&!g.ir.confirmedGuidance(m),"in-cone hot flare diverts IR and removes confirmed target guidance");t.x=-4;for(int i=0;i<1800&&m.alive;i++){g.elapsed+=.02;g.ir.tick(.02);g.fly(m,.02);}check(t.alive&&g.kills==0&&g.misses==1,"flare miss cannot kill aircraft");
 g=make();t=target(g);for(int shot=0;shot<9;shot++){g.chosenLauncher=shot/3;t.seen=g.elapsed;g.weaponLock(t);warm(g);g.fireWeapon(t);}check(g.ready()==0&&g.reserve==9&&g.reserved==9&&g.shots==9,"IR empties three launchers and reserves reload ammunition");for(Game.Launcher l:g.launchers)check(l.reload==90,"each empty launcher starts ninety-second reload");double wait=g.launchers[0].reload;g.running=false;g.tick(.1);check(g.launchers[0].reload==wait,"pause freezes shared launcher reload");g.running=true;g.contacts.clear();g.missiles.clear();g.nextSpawn=9999;for(int i=0;i<899;i++)g.tick(.1);check(g.ready()==0,"not early reload");for(int i=0;i<3;i++)g.tick(.1);check(g.ready()==9&&g.reserve==0&&g.reserved==0,"reload conserves shared ammunition");check(g.ready()+g.reserve+g.shots+g.lostAmmo==18,"IR conservation");g.start();check(g.irMode&&!g.ir.active&&g.ready()==9&&g.reserve==9&&g.ir.flares.isEmpty(),"IR loadout persists and mission state resets");g.toggleWeapon();check(g.irMode&&g.weapon.id.equals("ir6"),"in-mission toggle cannot grant a different weapon");
 g=make();t=target(g);g.weaponLock(t);warm(g);g.fireWeapon(t);m=g.missiles.get(0);t.x=-4;for(int i=0;i<150&&m.alive;i++)g.fly(m,.05);check(!m.alive&&t.alive&&g.misses==1,"seeker cannot track outside cone");
 g=make();Game.EnemyMissile e=new Game.EnemyMissile();e.id=101;e.weapon=4;e.x=e.px=4;e.alt=e.palt=1800;e.z=1.8;e.priority=false;e.radarTracked=true;e.samples=3;e.seen=0;g.enemyMissiles.add(e);g.weaponLock(e);warm(g);g.fireWeapon(e);m=g.missiles.get(0);for(int i=0;i<1200&&m.alive;i++){g.elapsed+=.02;g.fly(m,.02);if(e.alive)g.flyEnemy(e,.02);}check(g.kills==1&&g.radarHits==0,"IR intercepts hot incoming missile");
 g=make();t=target(g);g.weaponLock(t);warm(g);for(int i=0;i<600;i++)g.ir.tick(.05);check(!g.ir.active,"seeker timeout");System.out.println("PASS: IR acquisition, passive lock, aspect, terrain, ceiling, independent flight, flare distraction, reload, pause, timeout and reset");}
}
