package com.jb.radar;
import java.util.*;
public class IrstTest {
 static void check(boolean yes,String message){if(!yes)throw new AssertionError(message);}
 static class Certain extends Random {private static final long serialVersionUID=1;public double nextDouble(){return 0;}public double nextGaussian(){return 0;}}
 static Game make(){Properties p=new Properties();p.setProperty("radar.infrared","true");p.setProperty("radar.irstRangeKm","12");p.setProperty("radar.irstCapacity","2");p.setProperty("radar.irstUpdateSeconds","0.2");p.setProperty("radar.irstAcquireSeconds","0.4");p.setProperty("radar.irstTrackTimeoutSeconds","1");p.setProperty("radar.irstSwitchSeconds","0.15");Economy e=new Economy(new Economy.MemoryStore());e.equip("ir6");Game g=new Game(5,e,new Equipment(p));g.start();g.contacts.clear();g.enemyMissiles.clear();g.random=new Certain();g.radarOn=g.radarDesired=false;return g;}
 static Game.Contact contact(Game g,int id,double x,double y){Game.Contact t=new Game.Contact();t.id=id;t.type=0;t.x=x;t.y=y;t.alt=1800;t.heading=Math.PI/2;t.speed=0;t.flareBursts=0;t.nextFlare=9999;g.contacts.add(t);g.ai.assign(t,1,1,1,PilotAI.NO_WARNING_EQUIPMENT);return t;}
 static void tick(Game g,double seconds){int n=(int)Math.ceil(seconds/.05);for(int i=0;i<n;i++){g.elapsed+=.05;g.ir.tick(.05);}}
 static void start(Game g){g.ir.toggleIrst();tick(g,1);}
 static void fly(Game g,Game.Missile m,double seconds){for(int i=0;i<(int)Math.ceil(seconds/.05)&&m.alive;i++){g.elapsed+=.05;g.ir.fly(m,.05);}}
 public static void main(String[] args){
  Game base=new Game(3);base.start();check(base.ir.toggleIrst().equals("IRST NOT FITTED")&&!base.ir.irstOnline(),"existing Watchpost gains no invented IRST");
  Game g=make();Game.Contact a=contact(g,1,4,0),b=contact(g,2,5,0),c=contact(g,3,6,0);g.ir.toggleIrst();tick(g,.05);check(!g.ir.irstOnline()&&g.ir.observation(a)==null,"IRST respects switch delay");tick(g,.15);check(g.ir.irstOnline()&&!g.ir.irstTracked(a),"detection needs independent acquisition time");tick(g,.8);check(!g.radarReady()&&g.ir.irstCount()==2&&g.ir.irstTracked(a)&&g.ir.irstTracked(b)&&!g.ir.irstTracked(c),"IRST acquires two passive tracks while radar is off");check(g.ir.irstVisible(c)&&g.visible(c)&&g.nextTarget(null)!=null,"overflow passive detections remain selectable");check(a.samples==0&&a.detectionSamples==0&&a.palt==0,"passive sensor does not manufacture radar telemetry");check(g.ir.observation(a).rangeKnown==false&&g.ir.observationRange(a).equals("RANGE UNKNOWN"),"bearing-only passive observation never implies exact range");check(a.pilot.cues.isEmpty(),"passive sensing sends no aircraft warning");
  Infrared.IrstObservation before=g.ir.observation(a);a.y=1;tick(g,.05);check(g.ir.observation(a)==before,"IRST movement not sampled between update intervals");tick(g,.25);check(g.ir.observation(a).bearing!=before.bearing,"next passive measurement refreshes bearing");g.resetRadar();check(g.ir.irstVisible(a)&&g.ir.irstCount()==2,"radar RESET preserves independent passive tracks");
  g.ir.toggleIrst();double bearing=g.ir.observation(a).bearing;a.y=3;tick(g,.4);check(!g.ir.irstOnline()&&g.ir.observation(a).bearing==bearing,"IRST off freezes measured bearing");tick(g,1.3);check(!g.ir.irstVisible(a)&&g.ir.irstCount()==0,"passive stale data fades and expires");
  g=make();a=contact(g,1,13,-8);a.alt=100;start(g);check(g.ir.observation(a)==null,"passive sensor cannot see through terrain");a.x=4;a.y=0;a.alt=1800;g.ir.setConditions(1,0);tick(g,.5);check(g.ir.observation(a)==null,"obscuration suppresses passive acquisition");g.ir.setConditions(.8,.9);tick(g,1);check(g.ir.irstTracked(a),"moderate contrast change reduces performance without automatic failure");
  g=make();a=contact(g,1,4,0);start(g);check(g.ir.launchBlock(a)==null&&!g.ir.active&&!g.ir.locked,"valid IRST track enables lock-after-launch without battery lock");g.ir.launch(a);Game.Missile m=g.missiles.get(0);check(m.seekerState==Game.SeekerState.SEARCHING&&!m.autonomous&&!g.ir.confirmedGuidance(m),"launch begins SEARCHING rather than claiming acquisition");check(g.channels()==0&&!m.linkReserved&&!m.datalink&&g.ready()==11&&g.reserve==12,"passive flight consumes one round and no channels");check(Math.abs(m.estimateX-a.x)>1,"IRST-only launch estimate does not secretly copy true range");double launchX=m.estimateX;g.ir.toggleIrst();g.ir.cancel();g.resetRadar();check(m.estimateX==launchX,"sensor shutdown cannot rewrite missile launch estimate");fly(g,m,.2);check(m.seekerState==Game.SeekerState.SEARCHING,"own seeker has acquisition dwell");fly(g,m,.25);check(g.ir.confirmedGuidance(m)&&m.target==a,"own seeker acquires within range cone and sensitivity");check(g.guidanceLine(m)==Game.GuidanceLine.NONE,"IR has no external or target guidance line in beta UI");fly(g,m,15);check(!a.alive&&g.kills==1,"independent passive flight can intercept with radar and IRST off");
  g=make();a=contact(g,1,7,0);start(g);check(g.ir.launchBlock(a)==null,"selected far target has a valid passive cue");b=contact(g,2,4,0);b.alt=1100;g.ir.launch(a);m=g.missiles.get(0);fly(g,m,.5);check(g.ir.confirmedGuidance(m)&&m.target==b,"first valid encountered heat source can differ from selected contact");
  g=make();a=contact(g,1,4,0);start(g);g.ir.launch(a);m=g.missiles.get(0);a.x=-4;fly(g,m,.5);check(!g.ir.confirmedGuidance(m)&&m.seekerState==Game.SeekerState.SEARCHING,"seeker cannot magically find source behind cone");a.x=4;fly(g,m,.5);check(g.ir.confirmedGuidance(m),"seeker acquires when physical conditions become valid");a.x=-4;fly(g,m,.1);check(!g.ir.confirmedGuidance(m),"physical departure loses IR lock");a.x=4;fly(g,m,.5);check(g.ir.confirmedGuidance(m),"reacquisition requires dwell in valid search envelope");a.x=-4;fly(g,m,7);check(!m.alive&&a.alive&&g.misses==1,"search timeout ends failed engagement");
  g=make();a=contact(g,1,4,0);start(g);g.radarOn=g.radarDesired=true;double beforeSamples=a.detectionSamples;g.ir.cueRadar(a);check(a.radarCuePending&&a.detectionSamples==beforeSamples,"passive cue queues radar look without instant detection");g.observe(a);check(a.detectionSamples>beforeSamples,"actual radar observation can resolve passive cue");a.x=13;a.y=-8;a.alt=100;g.resetRadar();g.ir.cueRadar(a);g.observe(a);check(!g.detected(a),"passive cue cannot override radar terrain obstruction");
  System.out.println("PASS: independent IRST switching, sampling, acquisition/capacity, unknown range, coasting/reset, visibility/terrain, LOAL dwell, first heat source, independent flight, reacquisition and radar cueing");
 }
}
