package com.jb.radar;
import java.util.*;
/** Core rebuild rules: finite sensor estimates, separate channel pools and explicit seeker acquisition. */
public class RebuildTest {
 static void check(boolean value,String message){if(!value)throw new AssertionError(message);}
 static class Certain extends Random {public double nextDouble(){return 0;}public double nextGaussian(){return 0;}}
 static Game game(String... entries){Properties p=new Properties();for(int i=0;i<entries.length;i+=2)p.setProperty(entries[i],entries[i+1]);Game g=new Game(10,new Economy(new Economy.MemoryStore()),new Equipment(p));g.start();g.contacts.clear();g.enemyMissiles.clear();g.random=new Certain();return g;}
 static Game.Contact contact(Game g,int id,double x){Game.Contact t=new Game.Contact();t.id=id;t.x=t.px=x;t.y=t.py=0;t.alt=t.palt=3000;t.heading=t.pheading=-Math.PI/2;t.seen=g.elapsed;t.samples=4;t.quality=1;t.radarTracked=true;t.hadTrack=true;g.contacts.add(t);return t;}
 static Game.Missile launch(Game g,Game.Contact t){check(g.launchBlock(t)==null,"launch eligible: "+g.launchBlock(t));int count=g.missiles.size();g.launch(t);check(g.missiles.size()==count+1,"one missile launched");return g.missiles.get(count);}
 static void align(Game.Missile m,Game.Contact t){MissileMotion.aim(m,t.x-m.x,t.y-m.y,t.alt/1000-m.z);}
 static void firstObservations(){Game g=game();Game.Contact t=new Game.Contact();t.id=1;t.x=10;t.alt=3000;t.speed=1000;t.heading=2;g.contacts.add(t);g.observe(t);check(g.trackStage(t)==Game.TrackStage.ACQUIRING,"first observation acquires");check(t.pspeed==0&&g.speedText(t).equals("---")&&g.directionText(t).equals("---"),"first detection cannot know velocity");g.elapsed=5;check(g.displayX(t)==t.px&&g.displayY(t)==t.py,"no acquiring prediction");t.x=9;g.observe(t);check(g.stableTrack(t),"successive observations stabilize");check(Math.abs(t.pspeed-720)<1e-8&&Math.abs(t.pheading+Math.PI/2)<1e-8,"velocity inferred from measured displacement");check(g.identity(t)==0,"stable track does not identify enemy");g.elapsed=7;double predicted=g.displayX(t);t.x=20;t.heading=0;t.speed=3500;check(g.displayX(t)==predicted,"prediction never reads hidden movement");t.missed=1;t.missedAt=g.elapsed;check(g.trackStage(t)==Game.TrackStage.COASTING&&!g.stableTrack(t)&&g.launchBlock(t).equals("TRACK TOO WEAK"),"coasting cannot fire");g.elapsed=8;check(g.displayX(t)==predicted,"coasting stops last estimate at missed sweep");g.elapsed=28;g.maintainTracks();check(g.trackStage(t)==Game.TrackStage.LOST&&!g.tracked(t)&&g.visible(t),"lost frees slot and leaves brief last-known plot");t.x=8;g.observe(t);check(t.samples==1&&g.trackStage(t)==Game.TrackStage.ACQUIRING,"lost reacquires from first observation");}
 static void priority(){Game g=game("radar.tracks","2","radar.channels","2");Game.Contact player=contact(g,1,8),locked=contact(g,2,9),ordinary=contact(g,3,4);player.priority=true;g.illuminate(locked);Game.EnemyMissile incoming=new Game.EnemyMissile();incoming.id=101;incoming.x=incoming.px=15;incoming.alt=incoming.palt=3000;incoming.samples=4;incoming.seen=g.elapsed;incoming.quality=1;g.enemyMissiles.add(incoming);g.maintainTracks();check(g.tracked(locked)&&g.tracked(incoming)&&!g.tracked(player)&&!g.tracked(ordinary),"protected then incoming outrank player");g.release(locked);g.maintainTracks();check(g.tracked(incoming)&&g.tracked(player),"player priority outranks ordinary aircraft");}
 static void separateCapacity(){Game g=game("radar.illuminationChannels","1","radar.midcourseChannels","2","radar.supportedMissiles","2");Game.Contact first=contact(g,1,10),second=contact(g,2,11);g.illuminate(first);check(g.lockBlock(second).equals("NO FREE ILLUMINATION CHANNEL"),"illumination capacity per target");Game.Missile s1=launch(g,first),s2=launch(g,first);check(g.illuminationUsed()==1&&g.supportedMissilesUsed()==2,"two SARH share single illumination");check(g.launchBlock(first).equals("SUPPORTED MISSILE LIMIT"),"separate SARH missile cap");g.weapon=g.equipment.active;Game.Missile a1=launch(g,second);g.chosenLauncher=1;Game.Missile a2=launch(g,second);check(g.illuminationUsed()==1&&g.midcourseUsed()==2,"active pool independent and counts same-target missiles separately");check(g.launchBlock(second).equals("NO FREE SUPPORT CHANNEL"),"overflow blocks without spending ammo");check(a1.datalink&&a2.datalink&&!a1.supportReleased&&!a2.supportReleased,"overflow silently displaces nothing");g.releaseSupport(a1);check(g.midcourseUsed()==1&&!a1.datalink&&a2.datalink&&g.illuminationUsed()==1,"explicit release affects only selected active missile");g.releaseSupport(s1);check(g.illuminationUsed()==0&&!g.guided(s1)&&!g.guided(s2)&&g.midcourseUsed()==1,"SARH release reports all target support interrupted");}
 static void supportRecovery(){Game g=game();Game.Contact t=contact(g,1,10);g.illuminate(t);Game.Missile m=launch(g,t);g.release(t);double cachedX=m.estimateX;for(int i=0;i<10;i++)g.fly(m,.1);check(m.alive&&m.supportLostFor>.9&&g.missileState(m).equals("SUPPORT LOST"),"SARH coasts during recovery window");check(m.estimateX==cachedX,"unsupported SARH retains cached estimate");g.illuminate(t);g.fly(m,.1);check(m.alive&&m.supportLostFor==0&&g.guided(m),"SARH illumination recovery");g.release(t);for(int i=0;i<42;i++)g.fly(m,.1);check(!m.alive,"SARH recovery timeout ends engagement");
  g=game();g.weapon=g.equipment.active;t=contact(g,1,20);m=launch(g,t);t.radarTracked=false;g.fly(m,.1);check(m.alive&&g.midcourseUsed()==1&&!m.datalink&&m.seekerState==Game.SeekerState.MIDCOURSE,"lost active updates retain slot and do not force early seeker");t.radarTracked=true;g.fly(m,.1);check(m.datalink&&m.supportLostFor==0,"active updates recover within window");t.radarTracked=false;for(int i=0;i<42;i++)g.fly(m,.1);check(m.alive&&g.midcourseUsed()==0&&!m.datalink&&m.supportReleased,"expired updates become inertial and release reservation");}
 static void estimateIsolation(){Game a=game(),b=game();a.weapon=a.equipment.active;b.weapon=b.equipment.active;Game.Contact ta=contact(a,1,20),tb=contact(b,1,20);Game.Missile ma=launch(a,ta),mb=launch(b,tb);ta.x=23;ta.y=10;ta.alt=7000;tb.x=-15;tb.y=20;tb.alt=10000;for(int i=0;i<10;i++){a.fly(ma,.1);b.fly(mb,.1);}check(ma.seekerState==Game.SeekerState.MIDCOURSE&&mb.seekerState==Game.SeekerState.MIDCOURSE,"still midcourse");check(Math.abs(ma.x-mb.x)<1e-10&&Math.abs(ma.y-mb.y)<1e-10&&Math.abs(ma.z-mb.z)<1e-10,"midcourse flight independent of hidden target truth");}
 static void seeker(){Game g=game();g.weapon=g.equipment.active;Game.Contact t=contact(g,1,12);Game.Missile m=launch(g,t);m.x=8;m.z=3;MissileMotion.aim(m,-1,0,0);check(!g.guided(m)&&m.seekerState==Game.SeekerState.SEARCHING&&!m.autonomous,"transmitting does not imply acquisition outside FOV");check(g.missileState(m).equals("SEARCHING")&&g.guidanceLine(m)!=Game.GuidanceLine.TARGET_SOLID,"search has no confirmed seeker line");align(m,t);check(g.guided(m)&&m.autonomous&&m.seekerState==Game.SeekerState.ACQUIRED,"assigned target acquires within seeker envelope");check(g.midcourseUsed()==0&&g.missileState(m).equals("ACTIVE - TARGET ACQUIRED"),"actual acquisition releases channel");t.radarTracked=false;g.battery.parts[Battery.POWER].hp=0;check(g.guided(m),"acquired seeker independent of battery");t.y=20;g.fly(m,.05);check(!m.autonomous&&m.seekerState==Game.SeekerState.SEARCHING&&g.guidanceLine(m)==Game.GuidanceLine.NONE,"seeker loss clears confirmed line");for(int i=0;i<125;i++)g.fly(m,.05);check(!m.alive,"failed seeker search times out");}
 static void searchKeepsValidSupport(){Game g=game();g.weapon=g.equipment.active;Game.Contact t=contact(g,1,12);Game.Missile m=launch(g,t);m.x=8;m.z=3;t.y=20;align(m,newStationaryAim(12,0,3000));for(int i=0;i<45;i++)g.fly(m,.1);check(m.alive&&m.seekerState==Game.SeekerState.SEARCHING&&m.searchAge>4,"seeker search still within configured six seconds");check(m.datalink&&m.linkReserved&&m.supportLostFor==0&&g.midcourseUsed()==1,"searching retains valid updates beyond recovery timeout");}
 static Game.Contact newStationaryAim(double x,double y,double alt){Game.Contact t=new Game.Contact();t.x=x;t.y=y;t.alt=alt;return t;}
 static void rangeLimits(){Game g=game("radar.detectionAbsoluteKm","36","radar.trackingAbsoluteKm","28","radar.lockAbsoluteKm","20");Game.Contact t=contact(g,1,33);t.alt=t.palt=6000;double marginal=g.signal(t);check(marginal>0&&marginal<g.rangeFactor(20,30,36),"detection quality declines beyond effective");t.x=36.01;check(g.signal(t)==0,"absolute detection hard boundary");t.x=t.px=25;t.samples=4;g.maintainTracks();check(g.tracked(t)&&g.trackQuality(t)<1,"track may extend explicitly beyond nominal");t.px=29;g.maintainTracks();check(!g.tracked(t),"absolute track hard boundary");}
 public static void main(String[] args){firstObservations();priority();separateCapacity();supportRecovery();estimateIsolation();seeker();searchKeepsValidSupport();rangeLimits();System.out.println("PASS: acquiring/stable/coasting/lost estimates, priority, separate channel pools, explicit release, support recovery, seeker FOV/acquisition/loss, hidden-truth isolation and absolute limits");}
}
