package com.jb.radar;
public class TechTreeTest {
 static void ok(boolean b,String s){if(!b)throw new AssertionError(s);}
 static Economy funded(Economy.MemoryStore store,long dollars,long bp){Economy.State s=new Economy.State();s.dollars=dollars;s.bp=bp;s.lifetimeDollars=dollars;s.lifetimeBP=bp;store.save(s);return new Economy(store);}
 public static void main(String[] args){
  Equipment eq=Equipment.defaults();ok(eq.radar.name.equals("ADS-201 Watchpost")&&eq.radar.detectionKm==30&&eq.radar.trackingKm==24&&eq.radar.lockKm==16&&eq.radar.tracks==5&&eq.radar.channels==2&&eq.radar.launcherCapacity==3&&eq.radar.reserveRounds==12&&eq.radar.scanSpeed==1.00&&eq.radar.sweepSeconds()==10&&!eq.radar.infrared&&eq.radar.irLockKm==0&&eq.infrared!=null,"exact Watchpost stats, shared per-missile guidance capacity and no IRST");
  Equipment.Weapon r=eq.primary,s=eq.stonebolt;ok(r.name.equals("MIM-301 Rampart")&&r.guidanceSeconds==35&&r.maxSpeedKmh==2400&&r.maxG==14&&r.massKg==140&&r.maxAoADeg==12&&r.thrustN==18000,"exact Rampart stats");ok(s.name.equals("FIM-352 Stonebolt")&&s.guidanceSeconds==40&&s.maxSpeedKmh==2700&&s.maxG==12&&s.massKg==180&&s.maxAoADeg==10&&s.thrustN==22000,"exact Stonebolt stats");ok(r.guidance==Equipment.Guidance.RADAR&&s.guidance==Equipment.Guidance.RADAR&&r.radarMode==Equipment.RadarMode.SEMI_ACTIVE&&s.radarMode==Equipment.RadarMode.SEMI_ACTIVE,"both semi-active");ok(eq.active.radarMode==Equipment.RadarMode.ACTIVE&&eq.infrared.guidance==Equipment.Guidance.INFRARED,"three player guidance families available");for(Equipment.Weapon weapon:eq.all)ok(!weapon.id.equals("hawk"),"old HAWK removed");
  Economy.MemoryStore store=new Economy.MemoryStore();Economy e=new Economy(store);Economy.State w=e.snapshot();ok(TechTree.NODES.length==5&&TechTree.USA.equals("USA")&&w.owned.size()==4&&w.owned.contains("active")&&w.owned.contains("ir6")&&w.owned.contains("watchpost")&&w.owned.contains("rampart")&&w.equippedMissile.equals("rampart"),"free starters / USA only");ok(e.equip("stonebolt").contains("BUY")&&e.purchase("stonebolt").contains("RESEARCH"),"cannot equip or buy locked missile");ok(e.research("stonebolt").contains("NO BP"),"no negative BP");ok(e.research("invalid").contains("UNKNOWN"),"unknown IDs rejected");
  e=funded(store,1234,250);long earned=e.snapshot().lifetimeBP;e.research("stonebolt");w=e.snapshot();ok(w.bp==0&&TechTree.progress(w,TechTree.STONEBOLT)==250&&w.lifetimeBP==earned&&!w.owned.contains("stonebolt"),"partial research spends BP only");e=new Economy(store);ok(TechTree.progress(e.snapshot(),TechTree.STONEBOLT)==250,"partial research survives restart");e.beginMission();e.intercept("T-1",false);ok(e.equip("rampart").contains("MENU")&&e.purchase("stonebolt").contains("MENU")&&e.research("stonebolt").contains("MENU"),"loadout and spending cannot change mid-mission");e.finish(true,1);long cash=e.snapshot().dollars;e.research("stonebolt");w=e.snapshot();ok(TechTree.researched(w,TechTree.STONEBOLT)&&w.bp==50&&w.dollars==cash,"research consumes only needed BP and keeps remainder");e.research("stonebolt");ok(e.snapshot().bp==50,"no repeat research charge");e.purchase("stonebolt");w=e.snapshot();ok(w.owned.contains("stonebolt")&&w.dollars==cash-1500&&w.equippedMissile.equals("rampart"),"purchase separately from equip");e.purchase("stonebolt");ok(e.snapshot().dollars==cash-1500,"no duplicate purchase charge");e.equip("stonebolt");e=new Economy(store);ok(e.snapshot().equippedMissile.equals("stonebolt")&&e.snapshot().owned.contains("stonebolt"),"ownership/loadout persisted");
  Game g=new Game(6,e,eq);g.start();ok(g.weapon==eq.stonebolt&&!g.irMode&&g.ready()==12&&g.reserve==12,"selected missile loaded into shared launcher inventory");g.contacts.clear();Game.Contact t=GameTest.target(g,0);GameTest.lock(g,t);g.launch(t);Game.Missile m=g.missiles.get(0);ok(m.profile==eq.stonebolt,"actual projectile uses selected profile");for(int i=0;i<500&&m.alive;i++)g.fly(m,.1);ok(g.kills==1,"Stonebolt geometry intercept");g.finish(false);e.equip("rampart");g.start();ok(g.weapon==eq.primary,"switch back loads Rampart");g.contacts.clear();t=GameTest.target(g,0);GameTest.lock(g,t);g.launch(t);m=g.missiles.get(0);for(int i=0;i<500&&m.alive;i++)g.fly(m,.1);ok(g.kills==1&&m.profile==eq.primary,"Rampart geometry intercept");
  EconomyTest.FailingStore fs=new EconomyTest.FailingStore();e=funded(fs,2500,800);fs.fail=true;ok(e.research("stonebolt").contains("SAVE FAILED"),"failed research reported");ok(e.snapshot().bp==800&&TechTree.progress(e.snapshot(),TechTree.STONEBOLT)==0&&fs.load().bp==800,"failed research rolls back both fields");fs.fail=false;e.research("stonebolt");fs.fail=true;ok(e.purchase("stonebolt").contains("SAVE FAILED")&&e.snapshot().dollars==2500&&!e.snapshot().owned.contains("stonebolt"),"failed purchase preserves cash and ownership");fs.fail=false;e.purchase("stonebolt");fs.fail=true;e.equip("stonebolt");ok(e.snapshot().equippedMissile.equals("rampart"),"failed equip preserves old loadout");fs.fail=false;e.equip("stonebolt");e=new Economy(fs);ok(e.snapshot().equippedMissile.equals("stonebolt")&&e.snapshot().dollars==1000&&e.snapshot().bp==200,"retries commit each transaction once");
  e=funded(new Economy.MemoryStore(),100,600);e.research("stonebolt");ok(e.purchase("stonebolt").contains("NOT ENOUGH")&&e.snapshot().dollars==100,"insufficient dollars cannot buy");w=e.snapshot();w.owned.add("stonebolt");ok(!e.snapshot().owned.contains("stonebolt"),"snapshots do not leak mutable ownership");
  Economy.State old=new Economy.State();old.dollars=8765;old.bp=4321;old.lifetimeBP=9000;old.result="VICTORY";store.save(old);e=new Economy(store);w=e.snapshot();ok(w.dollars==8765&&w.bp==4321&&w.lifetimeBP==9000&&w.owned.contains("rampart")&&w.owned.contains("active")&&w.owned.contains("ir6")&&w.equippedMissile.equals("rampart"),"v0.8 migration preserves money and adds starters");TechTree.decode(w,"stonebolt=99999;bad=1;","stonebolt;bad;","not-real");ok(TechTree.progress(w,TechTree.STONEBOLT)==600&&w.owned.size()==5&&w.equippedMissile.equals("rampart"),"stored data normalization");String progress=TechTree.encodeResearch(w),owned=TechTree.encodeOwned(w);Economy.State decoded=new Economy.State();TechTree.decode(decoded,progress,owned,"stonebolt");ok(decoded.equippedMissile.equals("stonebolt")&&TechTree.researched(decoded,TechTree.STONEBOLT),"store encoding round-trip");
  System.out.println("PASS: exact USA stats, free starters, partial research, purchases, loadout, real interceptions, migration, retries and duplicate/insufficient-funds protection");
 }
}
