package com.jb.radar;
import java.util.*;
public class TrackingTest {
 static void check(boolean b,String s){if(!b)throw new AssertionError(s);}
 static Game active(int channels){return EquipmentTest.game(EquipmentTest.config("missile.rampart.radarMode","ACTIVE","missile.rampart.seekerKm","3","radar.channels",""+channels));}
 static Game.Contact target(Game g,int n){Game.Contact t=GameTest.target(g,n);t.x=t.px=18+n;return t;}
 public static void main(String[] args){
  Game g=active(2);Game.Contact t=target(g,0);t.priority=false;t.radarTracked=false;check(g.launchBlock(t).equals("TRACK REQUIRED"),"unallocated detection cannot fire");g.track(t);check(g.tracked(t)&&!g.hardLocked(t)&&g.channels()==0,"TWS alone uses no channel");check(g.lockBlock(t).contains("RANGE")&&g.launchBlock(t)==null,"active fires outside hard lock range within tracking envelope");g.launch(t);Game.Missile m=g.missiles.get(0);check(m.datalink&&g.channels()==1&&g.guided(m)&&!m.autonomous,"launch reserves midcourse channel");
  Game.Contact second=target(g,1),third=target(g,2);g.launch(second);check(g.channels()==2&&g.launchBlock(third).equals("NO DATALINK CHANNEL AVAILABLE"),"channel budget blocks third target");int shots=g.shots,ammo=g.ready();g.launch(third);check(g.shots==shots&&g.ready()==ammo,"denied launch spends no ammo");g.launch(t);check(g.shots==shots+1&&g.channels()==2,"missiles to same target share one channel");Game.Missile companion=g.missiles.get(2);
  m.x=t.x-1;m.y=t.y;m.z=t.alt/1000;check(g.guided(m)&&m.autonomous&&!m.datalink&&g.channels()==2,"first handoff keeps companion channel");companion.alive=false;g.chosenLauncher=1;check(g.channels()==1&&g.launchBlock(third)==null,"last midcourse missile releases target channel");t.radarTracked=false;g.battery.parts[Battery.POWER].hp=0;check(g.guided(m),"active seeker survives radar and power loss");
  g=active(1);t=target(g,0);g.launch(t);m=g.missiles.get(0);t.radarTracked=false;check(!g.guided(m)&&g.channels()==0,"lost track interrupts midcourse and frees channel");second=target(g,1);second.x=second.px=9;g.illuminate(second);t.radarTracked=true;check(!g.guided(m)&&g.channels()==1,"reacquisition does not steal a hard-lock channel");g.release(second);check(g.guided(m)&&g.channels()==1,"midcourse recovers when slot available");m.age=g.weapon.guidanceSeconds+.1;check(!g.guided(m)&&g.channels()==0,"expired guidance releases channel");
  g=active(1);t=target(g,0);t.x=t.px=9;g.launch(t);m=g.missiles.get(0);g.illuminate(t);check(g.hardLocked(t)&&g.channels()==1,"hard lock shares current target channel");g.release(t);check(g.tracked(t)&&!g.hardLocked(t)&&g.guided(m),"release returns to TWS without breaking active updates");g.illuminate(t);m.x=8;m.z=3;check(g.guided(m)&&m.autonomous&&g.hardLocked(t)&&g.channels()==1,"seeker does not clear manual hard lock");g.release(t);check(g.channels()==0&&g.guided(m),"manual lock release leaves active seeker independent");
  g=new Game(3);g.start();g.contacts.clear();t=GameTest.target(g,0);check(g.launchBlock(t).equals("LOCK REQUIRED"),"semi-active cannot fire in TRACK");g.illuminate(t);g.launch(t);m=g.missiles.get(0);check(g.guided(m),"semi-active supported by lock");g.release(t);check(g.tracked(t)&&!g.hardLocked(t)&&!g.guided(m),"TWS alone cannot guide semi-active missile");g.illuminate(t);check(g.guided(m),"hard lock recovery supports missile");t.seen=-100;g.maintainTracks();check(!g.tracked(t)&&!g.hardLocked(t)&&g.channels()==0,"track loss clears both states");
  g=active(0);t=target(g,0);check(g.launchBlock(t).equals("NO DATALINK CHANNEL AVAILABLE"),"zero-channel battery cannot launch active midcourse");
  Properties p=new Properties();p.setProperty("ai.trackingCue","true");g=new Game(1,new Economy(new Economy.MemoryStore()),Equipment.defaults(),new CombatRules(p));g.start();g.contacts.clear();g.random=new AIBehaviorTest.Certain();t=GameTest.target(g,0);t.priority=false;t.radarTracked=false;g.ai.assign(t,5,1,2);g.track(t);check(t.pilot.cues.size()==1&&t.pilot.cues.get(0).kind==PilotAI.Warning.TRACK,"TRACK generates only tracking cue");g.illuminate(t);check(t.pilot.cues.size()==2&&t.pilot.cues.get(1).kind==PilotAI.Warning.LOCK,"hard lock is a separate warning");g.release(t);check(t.pilot.cues.size()==2&&!g.hardLocked(t),"release invents no new lock warning");
  // Active TWS engagement must reach a real moving projectile handoff/interception.
  g=active(1);t=GameTest.target(g,0);g.launch(t);m=g.missiles.get(0);boolean handoff=false;for(int i=0;i<2000&&m.alive;i++){g.fly(m,.02);handoff|=m.autonomous;check(g.channels()<=1,"flight channel cap");}check(handoff&&g.kills==1&&!t.alive&&g.channels()==0,"active TWS flight acquires, intercepts and frees channel");
  System.out.println("PASS: TRACK/LOCK states, active TWS launches, shared channels, handoff/recovery/expiry, SARH lock loss and separate AI cues");
 }
}
