package com.jb.radar;
import java.util.*;
/** Fictional warning fits and independently sensed IR acquisition, not real aircraft capability claims. */
public class WarningProfileTest {
 static void check(boolean value,String message){if(!value)throw new AssertionError(message);}
 static class Certain extends Random {private static final long serialVersionUID=1;public double nextDouble(){return 0;}public double nextGaussian(){return 0;}}
 static Game game(){Game g=new Game(19);g.start();g.contacts.clear();g.enemyMissiles.clear();g.random=new Certain();return g;}
 static Game.Contact target(Game g){Game.Contact t=GameTest.target(g,0);t.x=t.px=4;t.y=t.py=0;t.alt=t.palt=1800;t.heading=t.pheading=Math.PI/2;t.flareBursts=0;t.nextFlare=9999;g.ai.assign(t,5,2,2);return t;}
 static void equipIR(Game g){g.weapon=g.equipment.infrared;g.irMode=true;g.ir.reset();}
 static void warm(Game g){for(int i=0;i<72;i++){g.elapsed+=.05;g.ir.tick(.05);}}
 static Game.Missile launchIR(Game g,Game.Contact t){equipIR(g);g.ir.begin(t);warm(g);check(g.ir.locked,"IR seeker acquires radar-cued contact");check(g.ir.launchBlock(t)==null,"locked IR ready");g.ir.launch(t);return g.missiles.get(g.missiles.size()-1);}
 public static void main(String[] args){
  Game g=game();Game.Contact t=target(g);g.ai.assign(t,5,2,2,PilotAI.NO_WARNING_EQUIPMENT);g.ai.warn(t,PilotAI.Warning.TRACK,true);g.ai.warn(t,PilotAI.Warning.LOCK,true);g.ai.launchWarning(t,false);g.ai.radarPresence(t);g.ai.activeSeekerWarning(t);Game.Missile near=new Game.Missile();near.x=t.x-.2;near.y=t.y;near.z=t.alt/1000;g.ai.visualWarning(t,near);check(t.pilot.cues.isEmpty()&&t.pilot.awareness==PilotAI.Awareness.UNAWARE,"aircraft without suitable equipment cannot read hidden actions");
  g.ai.assign(t,5,2,2,PilotAI.BASIC_RWR);g.ai.radarPresence(t);check(t.pilot.cues.size()==1&&t.pilot.cues.get(0).kind==PilotAI.Warning.SEARCH,"search emissions create presence cue");check(t.pilot.awareness==PilotAI.Awareness.UNAWARE,"reaction delay before awareness");g.ai.tick(t,.05);check(t.pilot.awareness==PilotAI.Awareness.UNAWARE,"no instant warning response");g.elapsed=2;g.ai.tick(t,.05);check(t.pilot.awareness==PilotAI.Awareness.ALERTED&&t.pilot.state==PilotAI.State.CAUTIOUS,"radar presence creates caution without forcing evasion");check(!g.ai.warn(t,PilotAI.Warning.TRACK,true),"TWS tracking never auto-warns");g.ai.warn(t,PilotAI.Warning.LOCK,true);check(t.pilot.cues.size()==1&&t.pilot.cues.get(0).kind==PilotAI.Warning.LOCK,"compatible RWR recognizes fire control separately");
  g=game();t=target(g);t.x=t.px=12;g.ai.launchWarning(t,false);g.ai.launchWarning(t,true);check(t.pilot.cues.isEmpty(),"distant launch is not a universal radar warning");g.ai.assign(t,5,2,2,PilotAI.LIMITED_RWR);g.ai.activeSeekerWarning(t);check(t.pilot.cues.isEmpty(),"incompatible receiver misses active seeker");g.ai.assign(t,5,2,2,PilotAI.BASIC_RWR);near.profile=g.equipment.active;near.x=11;near.z=1.8;near.vx=1;near.speed=.3;near.seekerState=Game.SeekerState.SEARCHING;g.missiles.add(near);g.ai.activeSeekerWarning(t,near);check(t.pilot.cues.isEmpty(),"missile object alone does not bypass physical receiver");for(int step=0;step<20;step++){g.elapsed+=.05;g.sensors.tick(.05);}check(t.pilot.cues.size()==1&&t.pilot.cues.get(0).kind==PilotAI.Warning.ACTIVE_SEEKER,"compatible receiver detects nearby missile transmitter after acquisition delay");
  g=game();t=target(g);equipIR(g);check(!g.equipment.radar.infrared&&g.equipment.radar.irLockKm==0,"Watchpost still has no IRST");g.ir.begin(t);check(g.ir.active&&!g.ir.locked,"own seeker starts without IRST");check(g.ir.launchBlock(t).equals("VALID THERMAL CUE REQUIRED"),"radar selection requires actual thermal cue");warm(g);check(g.ir.locked&&t.pilot.cues.isEmpty(),"passive IR lock sends no radar warning");check(g.ir.lockRange()>0,"own seeker range independent of zero IRST range");g.ir.launch(t);Game.Missile m=g.missiles.get(0);check(g.ready()==11&&g.reserve==12&&g.channels()==0,"IR uses selected generic launcher but no guidance channels");check(!g.ir.confirmedGuidance(m),"own seeker searches after launch");for(int i=0;i<10;i++)g.ir.fly(m,.05);check(g.ir.confirmedGuidance(m),"independent seeker acquired after dwell");check(m.estimateValid&&Math.abs(m.estimateX-t.x)<1e-6,"displayable seeker estimate recorded");t.seen=-999;g.battery.parts[Battery.RADAR].hp=0;for(int i=0;i<500&&m.alive;i++){g.elapsed+=.02;g.ir.fly(m,.02);}check(!t.alive&&g.kills==1,"IR flight survives radar track and equipment loss");
  g=game();t=target(g);equipIR(g);g.launchers[0].reload=20;check(g.ir.beginBlock(t).equals("LAUNCHER RELOADING"),"IR obeys shared launcher readiness");g.launchers[0].reload=0;g.battery.parts[Battery.L1].hp=0;check(g.ir.beginBlock(t).equals("LAUNCHER DISABLED"),"IR obeys launcher damage");
  g=game();t=target(g);equipIR(g);t.px=-4;check(g.ir.begin(t).contains("COOLING"),"cached cue accepted");warm(g);check(!g.ir.locked,"wrong cached bearing cannot magically acquire target behind seeker");
  g=game();t=target(g);m=launchIR(g,t);for(int i=0;i<10;i++)g.ir.fly(m,.05);double saved=t.x;t.x=-4;g.ir.fly(m,.1);check(!g.ir.confirmedGuidance(m)&&m.seekerState==Game.SeekerState.SEARCHING,"outside FOV loses seeker line");check(m.estimateX==saved,"lost seeker does not leak hidden target position");t.x=saved;for(int i=0;i<5;i++)g.ir.fly(m,.1);check(g.ir.confirmedGuidance(m),"target can reacquire within bounded search cone");t.x=-4;for(int i=0;i<100&&m.alive;i++)g.ir.fly(m,.1);check(!m.alive&&t.alive,"unrecovered seeker fails after timeout");
  g=game();t=target(g);equipIR(g);double clear=g.ir.heat(t,0,0,.115);g.ir.setConditions(.8,.9);check(g.ir.heat(t,0,0,.115)>0&&g.ir.heat(t,0,0,.115)<clear,"thermal contrast changes quality smoothly");g.ir.setConditions(1,0);check(!g.ir.canSee(t),"opaque visibility prevents acquisition");
  Properties p=new Properties();p.setProperty("radar.infrared","true");p.setProperty("radar.irLockKm","9");g=new Game(4,new Economy(new Economy.MemoryStore()),new Equipment(p));g.start();g.contacts.clear();t=target(g);equipIR(g);t.samples=0;t.seen=-999;g.ir.toggleIrst();for(int i=0;i<70;i++){g.elapsed+=.05;g.ir.tick(.05);}Infrared.IrstObservation observation=g.ir.observation(t);check(observation!=null&&!observation.rangeKnown&&observation.contactId==t.id,"IRST maintains identity without false exact range");check(g.ir.observationRange(t).equals("RANGE UNKNOWN"),"IRST-only range explicitly unknown");check(g.ir.beginBlock(t)==null,"passive observation can cue own seeker without radar");
  System.out.println("PASS: receiver profiles, delayed awareness, silent TWS/IR, physical launch cues, IR radar-cue acquisition and post-launch search, shared launchers, seeker cone/recovery, cached guidance and passive unknown range");
 }
}
