package com.jb.radar;
import android.app.*;import android.os.*;import android.view.*;import android.graphics.*;import android.media.*;import java.util.*;
public class MainActivity extends Activity {
 Radar view; MediaPlayer menuMusic;boolean foreground,musicReady,hasFocus;AudioManager audioManager;
 final AudioManager.OnAudioFocusChangeListener focusListener=change->{hasFocus=change==AudioManager.AUDIOFOCUS_GAIN;if(hasFocus){if(foreground&&view!=null&&!view.started&&musicReady)menuMusic.start();}else if(menuMusic!=null&&musicReady&&menuMusic.isPlaying())menuMusic.pause();};
 void syncMusic(){boolean wanted=foreground&&view!=null&&!view.started;if(!wanted){if(menuMusic!=null&&musicReady&&menuMusic.isPlaying())menuMusic.pause();if(hasFocus&&audioManager!=null)audioManager.abandonAudioFocus(focusListener);hasFocus=false;return;}if(menuMusic==null){try{audioManager=(AudioManager)getSystemService(AUDIO_SERVICE);menuMusic=new MediaPlayer();menuMusic.setAudioAttributes(new AudioAttributes.Builder().setUsage(AudioAttributes.USAGE_GAME).setContentType(AudioAttributes.CONTENT_TYPE_MUSIC).build());try(android.content.res.AssetFileDescriptor fd=getAssets().openFd("menu_theme.mp3")){menuMusic.setDataSource(fd.getFileDescriptor(),fd.getStartOffset(),fd.getLength());}menuMusic.setLooping(true);menuMusic.setVolume(.65f,.65f);menuMusic.setOnPreparedListener(m->{musicReady=true;syncMusic();});menuMusic.setOnErrorListener((m,w,e)->{musicReady=false;return true;});menuMusic.prepareAsync();}catch(Exception e){if(menuMusic!=null)menuMusic.release();menuMusic=null;musicReady=false;}}if(musicReady){if(!hasFocus)hasFocus=audioManager.requestAudioFocus(focusListener,AudioManager.STREAM_MUSIC,AudioManager.AUDIOFOCUS_GAIN)==AudioManager.AUDIOFOCUS_REQUEST_GRANTED;if(hasFocus&&!menuMusic.isPlaying())menuMusic.start();}}

 public void onCreate(Bundle b){super.onCreate(b);getWindow().setFlags(1024,1024);getWindow().addFlags(128);view=new Radar();setContentView(view);view.setOnApplyWindowInsetsListener((v,i)->{int l=i.getSystemWindowInsetLeft(),r=i.getSystemWindowInsetRight(),t=i.getSystemWindowInsetTop(),bt=i.getSystemWindowInsetBottom();if(Build.VERSION.SDK_INT>=28&&i.getDisplayCutout()!=null){DisplayCutout d=i.getDisplayCutout();l=Math.max(l,d.getSafeInsetLeft());r=Math.max(r,d.getSafeInsetRight());t=Math.max(t,d.getSafeInsetTop());bt=Math.max(bt,d.getSafeInsetBottom());}v.setPadding(l,t,r,bt);return i;});}
 public void onResume(){super.onResume();foreground=true;syncMusic();if(view!=null){view.last=System.nanoTime();view.invalidate();}}
 public void onPause(){foreground=false;syncMusic();super.onPause();if(view!=null){view.paused=true;view.last=0;}}
 public void onDestroy(){if(menuMusic!=null){menuMusic.release();menuMusic=null;}if(view!=null&&view.tone!=null)view.tone.release();super.onDestroy();}
 @Override public void onBackPressed(){view.paused=true;view.help=false;view.invalidate();}
 class Radar extends View {
  final int green=0xff00ff00,muted=0xff70b870,amber=0xffeeeeee,red=0xffffffff,bg=0xff000000,border=0xff164516,panel=0xff020a02;
  Paint p=new Paint(3);Game game=new Game(System.nanoTime());Game.Contact selected;ArrayList<Btn> buttons=new ArrayList<>();long last;float scale,ox,oy;boolean paused=false,started=false,sound=false,ended=false,help=false;int speed=1,best=getPreferences(0).getInt("hawk_best",0);String notice="MISSION 1 / HAWK BATTERY";ToneGenerator tone;Bitmap launcherIcon;
  class Btn{RectF r;String id;boolean enabled;Btn(float x,float y,float w,float h,String i,boolean e){r=new RectF(x,y,x+w,y+h);id=i;enabled=e;}}
  Radar(){super(MainActivity.this);setFocusable(true);try(java.io.InputStream stream=getAssets().open("hawk_launcher.png")){BitmapFactory.Options opts=new BitmapFactory.Options();opts.inSampleSize=4;launcherIcon=BitmapFactory.decodeStream(stream,null,opts);}catch(java.io.IOException e){launcherIcon=null;}try{tone=new ToneGenerator(AudioManager.STREAM_MUSIC,30);}catch(Exception e){}}
  void text(Canvas c,String s,float x,float y,float size,int color){p.setColor(color);p.setStyle(Paint.Style.FILL);p.setTypeface(Typeface.MONOSPACE);p.setTextSize(size);c.drawText(s,x,y,p);}
  void rect(Canvas c,float x,float y,float w,float h,int col,boolean fill){p.setColor(col);p.setStyle(fill?Paint.Style.FILL:Paint.Style.STROKE);p.setStrokeWidth(1);c.drawRoundRect(new RectF(x,y,x+w,y+h),7,7,p);p.setStyle(Paint.Style.FILL);}
  void line(Canvas c,float x,float y,float xx,float yy,int col){p.setColor(col);p.setStrokeWidth(1);c.drawLine(x,y,xx,yy,p);}
  void circle(Canvas c,float x,float y,float r,int col,boolean fill){p.setColor(col);p.setStyle(fill?Paint.Style.FILL:Paint.Style.STROKE);p.setStrokeWidth(1);c.drawCircle(x,y,r,p);p.setStyle(Paint.Style.FILL);}
  void button(Canvas c,String id,String label,float x,float y,float w,boolean enabled){rect(c,x,y,w,48,enabled?border:0xff061006,true);rect(c,x,y,w,48,enabled?muted:border,false);text(c,label,x+12,y+30,15,enabled?green:muted);buttons.add(new Btn(x,y,w,48,id,enabled));}
  String fmt(String s,Object...o){return String.format(Locale.US,s,o);}void beep(){if(sound&&tone!=null)tone.startTone(ToneGenerator.TONE_PROP_BEEP,60);}
  protected void onDraw(Canvas c){super.onDraw(c);long now=System.nanoTime();if(last!=0&&!paused&&started){double remaining=Math.min(.15,(now-last)/1e9)*speed;while(remaining>0){double d=Math.min(.05,remaining);game.tick(d);remaining-=d;}}last=now;
   if(game.finished&&!ended){ended=true;if(game.score>best){best=game.score;getPreferences(0).edit().putInt("hawk_best",best).apply();}}
   float aw=getWidth()-getPaddingLeft()-getPaddingRight(),ah=getHeight()-getPaddingTop()-getPaddingBottom();scale=Math.min(aw/1280f,ah/720f);ox=getPaddingLeft()+(aw-1280*scale)/2;oy=getPaddingTop()+(ah-720*scale)/2;c.drawColor(bg);c.save();c.translate(ox,oy);c.scale(scale,scale);buttons.clear();if(!started){mainMenu(c);c.restore();return;}
   text(c,"AIR DEFAME 101",20,32,25,green);text(c,"MISSION 01   /   MIM-23A BATTERY",20,54,12,muted);text(c,fmt("RADAR %d km",game.maxRange),445,32,20,game.health>25?green:red);text(c,fmt("%02d:%02d",(int)game.elapsed/60,(int)game.elapsed%60),622,32,22,amber);
   button(c,"speed",speed+"x TIME",770,11,140,true);button(c,"help","GUIDE",922,11,145,true);button(c,"pause","PAUSE",1080,11,180,started&&!game.finished);
   telemetry(c);scope(c);engagement(c);launchers(c);controlBar(c);if(game.elapsed<game.impactUntil){rect(c,405,180,390,130,bg,true);rect(c,405,180,390,130,green,false);int flash=((int)(game.elapsed*5)%2==0)?green:amber;text(c,"RADAR IMPACT",430,220,27,flash);text(c,"SYSTEM DAMAGE DETECTED",430,254,18,flash);text(c,fmt("RANGE REDUCED -%.0f km",game.lastDamage),430,284,16,flash);}
   text(c,notice,20,717,11,amber);
   if(!started||paused||game.finished)overlay(c);c.restore();if(isShown())postInvalidateDelayed(33);
  }
  void mainMenu(Canvas c){text(c,"AIR DEFAME 101",410,285,44,green);rect(c,440,366,400,84,border,true);rect(c,440,366,400,84,green,false);text(c,"PLAY",595,420,30,green);buttons.add(new Btn(440,366,400,84,"start",true));}
  void controlBar(Canvas c){boolean active=!paused&&!game.finished;button(c,"next","NEXT TARGET",20,654,244,active);button(c,"track",selected!=null&&selected.priority?"TRACKING":"TRACK",276,654,200,active&&game.visible(selected));button(c,"illuminate",selected!=null&&selected.illuminated?"LOCKED":"LOCK",488,654,200,active&&game.liveTrack(selected)&&selected.priority&&!selected.illuminated&&game.channels()<2);button(c,"launch","FIRE",700,654,220,active&&game.launchBlock(selected)==null);button(c,"range","RANGE LIMIT: "+game.range+" KM",932,654,328,active&&game.maxRange>0);}
  void telemetry(Canvas c){rect(c,20,74,315,484,border,false);text(c,"S1 / TARGET ANALYSIS",36,100,17,green);text(c,"ALT km",36,125,12,muted);float gx=69,gy=140,gw=244,gh=98;for(int i=0;i<=4;i++){float x=gx+gw*i/4,y=gy+gh*i/4;line(c,x,gy,x,gy+gh,border);line(c,gx,y,gx+gw,y,border);text(c,""+(20-i*5),38,y+4,10,muted);text(c,""+(i*600),x-10,gy+gh+18,10,muted);}text(c,"SPEED km/h",188,278,11,muted);for(Game.Contact t:game.contacts)if(game.visible(t))circle(c,gx+gw*(float)Math.min(1,t.pspeed/2400),gy+gh*(float)(1-Math.min(1,t.palt/20000)),t==selected?5:3,t==selected?amber:green,true);
   if(selected==null){text(c,"SELECT AN AIRCRAFT",36,317,16,amber);String[] rows={"NEXT TARGET cycles by range.","TRACK adds a priority target.","LOCK assigns a fire channel.","FIRE launches a missile.","Short range improves precision.","", "Two channels / 18 missiles.","Watch for incoming missiles."};for(int i=0;i<rows.length;i++)text(c,rows[i],36,350+i*24,12,muted);return;}
   Game.Contact t=selected;text(c,fmt("T-%03d / %s",t.id,game.trackState(t)),36,307,14,amber);text(c,game.identification(t),36,332,13,green);text(c,fmt("RNG %.1f km  ALT %.0f m",t.measuredRange(),t.palt),36,355,13,muted);text(c,fmt("SPD %.0f km/h  HDG %03d",t.pspeed,((int)Math.toDegrees(t.pheading)%360+360)%360),36,377,13,muted);text(c,fmt("SIZE %.1f m / V/S %+.0f m/s",t.psize,t.pclimb),36,398,12,muted);
   Integer[] order={0,1,2,3,4};Arrays.sort(order,(x,y)->Double.compare(t.probabilities[y],t.probabilities[x]));for(int i=0;i<5;i++){int k=order[i];text(c,fmt("%-10s %2.0f%%",Game.NAMES[k],t.probabilities[k]*100),36,422+i*18,12,i==0?green:muted);}text(c,fmt("UNKNOWN FACTOR %.0f%%",t.probabilities[5]*100),36,521,13,amber);text(c,game.payload(t),36,547,12,muted);
  }
  void scope(Canvas c){float cx=595,cy=302,r=183;rect(c,347,74,496,484,border,false);text(c,"S2 / SEARCH RADAR",365,100,17,green);text(c,game.range+" km",750,100,14,amber);circle(c,cx,cy,r,0xff000600,true);
   // Terrain is a fixed fictional map, rendered only within the circular scope.
   c.save();Path clip=new Path();clip.addCircle(cx,cy,r,Path.Direction.CW);c.clipPath(clip);for(int x=-80;x<80;x+=3)for(int y=-80;y<80;y+=3){double height=Game.terrain(x,y);if(height>180){int a=(int)Math.min(100,height/12);rect(c,cx+x/(float)game.range*r,cy+y/(float)game.range*r,3*r/game.range+1,3*r/game.range+1,Color.argb(a,35,100,35),true);}}c.restore();
   for(int i=1;i<=4;i++){circle(c,cx,cy,r*i/4,border,false);text(c,fmt("%.0f",game.range*i/4.0),cx+5,cy-r*i/4+13,10,muted);}if(game.range>=25)circle(c,cx,cy,r*25/game.range,0xffa0d0a0,false);line(c,cx-r,cy,cx+r,cy,border);line(c,cx,cy-r,cx,cy+r,border);text(c,"N",cx-5,cy-r-6,12,green);
   for(int i=0;i<32;i++){p.setColor(Color.argb(55-i,0,255,0));p.setStyle(Paint.Style.FILL);c.drawArc(new RectF(cx-r,cy-r,cx+r,cy+r),(float)Math.toDegrees(game.sweep)-90-i,1.3f,true,p);}line(c,cx,cy,cx+(float)Math.sin(game.sweep)*r,cy-(float)Math.cos(game.sweep)*r,green);
   rect(c,cx-5,cy-5,10,10,green,true);
   for(Game.Contact t:game.contacts)if(game.visible(t)){float x=cx+(float)t.px/game.range*r,y=cy+(float)t.py/game.range*r;int col=game.elapsed-t.seen>7?muted:t.illuminated?amber:green;if(t.illuminated)line(c,cx,cy,x,y,0xff567856);aircraftGlyph(c,x,y,t,col);if(t.priority)circle(c,x,y,13,col,false);if(t==selected)rect(c,x-12,y-12,24,24,amber,false);text(c,fmt("%03d",t.id),x+9,y-8,12,col);}
   for(Game.Missile m:game.missiles)if(m.alive&&Math.hypot(m.x,m.y)<=game.range){float x=cx+(float)m.x/game.range*r,y=cy+(float)m.y/game.range*r;missileGlyph(c,x,y,Math.atan2(m.target.x-m.x,-(m.target.y-m.y)),green);text(c,"MIM-23",x+7,y,9,green);}
   for(Game.EnemyMissile m:game.enemyMissiles)if(game.visible(m)){float x=cx+(float)m.px/game.range*r,y=cy+(float)m.py/game.range*r;missileGlyph(c,x,y,Math.atan2(-m.px,m.py),amber);text(c,"M-"+m.id,x+8,y,10,amber);}
   text(c,"PALE RING: 25 km / SHADE: TERRAIN",367,525,12,muted);text(c,"DIAMOND: UNKNOWN / WHITE MSL: INCOMING",367,548,11,muted);
  }
  void aircraftGlyph(Canvas c,float x,float y,Game.Contact t,int col){c.save();c.translate(x,y);c.rotate((float)Math.toDegrees(t.pheading));if(t.confidence<.75||game.elapsed-t.seen>7){line(c,0,-8,6,0,col);line(c,6,0,0,8,col);line(c,0,8,-6,0,col);line(c,-6,0,0,-8,col);}else{int type=t.guess;float wing=type==0?11:type==1?6:type==2?9:10;float sweep=type==0?1:type==1?6:type==2?4:type==3?5:6;line(c,0,-12,0,11,col);line(c,0,-5,-wing,sweep,col);line(c,-wing,sweep,0,3,col);line(c,0,-5,wing,sweep,col);line(c,wing,sweep,0,3,col);line(c,-4,9,4,9,col);}c.restore();}
  void missileGlyph(Canvas c,float x,float y,double heading,int col){c.save();c.translate(x,y);c.rotate((float)Math.toDegrees(heading));line(c,0,-6,0,6,col);line(c,-3,-1,0,-6,col);line(c,3,-1,0,-6,col);c.restore();}
  void engagement(Canvas c){rect(c,855,74,405,484,border,false);text(c,"FIRE CONTROL / "+game.channels()+" OF 2",874,101,17,green);int row=0;for(Game.Contact t:game.contacts)if(t.alive&&t.illuminated){text(c,fmt("CH%d T-%03d / %d MISSILES",++row,t.id,game.inbound(t)),874,108+row*22,13,amber);}while(row<2)text(c,"CH"+(++row)+" AVAILABLE",874,108+row*22,13,muted);
   button(c,"release","RELEASE LOCK",874,166,178,selected!=null&&selected.illuminated&&!paused&&!game.finished);text(c,"THREAT",1070,183,12,muted);text(c,selected==null?"--":game.threat(selected),1070,204,13,amber);
   text(c,"PRIORITY TARGETS",874,239,15,green);ArrayList<Game.Contact> a=new ArrayList<>();for(Game.Contact t:game.contacts)if(t.priority&&t.alive)a.add(t);a.sort((x,y)->Double.compare(x.measuredRange(),y.measuredRange()));for(int i=0;i<Math.min(4,a.size());i++){Game.Contact t=a.get(i);text(c,fmt("T-%03d %-9s %4.1f km %s",t.id,t.confidence<.3?"UNKNOWN":Game.NAMES[t.guess],t.measuredRange(),game.trackState(t)),874,265+i*22,11,t==selected?amber:muted);}if(a.isEmpty())text(c,"Press TRACK to prioritize a contact.",874,265,12,muted);if(a.size()>4)text(c,"+"+(a.size()-4)+" more tracked",874,355,11,muted);
   Game.EnemyMissile incoming=null;for(Game.EnemyMissile m:game.enemyMissiles)if(game.visible(m)&&(incoming==null||Math.hypot(m.px,m.py)<Math.hypot(incoming.px,incoming.py)))incoming=m;
   if(incoming!=null){text(c,"INCOMING MISSILE  M-"+incoming.id,874,387,17,amber);text(c,game.missileName(incoming),874,410,15,green);text(c,fmt("RNG %.1f km / SPD %.0f km/h",Math.hypot(incoming.px,incoming.py),incoming.speed*3600),874,434,12,muted);text(c,"HEADING: RADAR SITE",874,455,12,amber);}else{text(c,"NO DETECTED INCOMING MISSILES",874,392,13,muted);text(c,fmt("KILLS %d / HITS %d / SCORE %d",game.kills,game.radarHits,game.score),874,424,13,green);}
   String why=game.launchBlock(selected);text(c,why==null?"MIM-23A READY / LAUNCHER "+(game.chosenLauncher+1):why,874,484,11,amber);int n=game.log.size();for(int j=Math.max(0,n-2);j<n;j++){String msg=game.log.get(j);text(c,msg.length()>44?msg.substring(0,44):msg,874,516+(j-Math.max(0,n-2))*22,11,muted);}
  }
  void launchers(Canvas c){for(int i=0;i<3;i++){float x=20+i*282;Game.Launcher l=game.launchers[i];rect(c,x,570,270,73,bg,true);rect(c,x,570,270,73,i==game.chosenLauncher?amber:border,false);
   if(launcherIcon!=null){float iw=122,ih=iw*launcherIcon.getHeight()/launcherIcon.getWidth();p.setFilterBitmap(true);p.setAlpha(l.ammo==0?100:255);c.drawBitmap(launcherIcon,null,new RectF(x+7,606.5f-ih/2,x+7+iw,606.5f+ih/2),p);p.setAlpha(255);}
   String status=l.reload>0?fmt("RELOAD %02ds",(int)Math.ceil(l.reload)):l.ammo==0?"EMPTY":"READY";
   text(c,"L"+(i+1),x+141,591,16,i==game.chosenLauncher?amber:green);text(c,l.ammo+" / 3",x+210,591,13,muted);text(c,status,x+141,611,12,l.reload>0?amber:green);
   for(int j=0;j<3;j++)rect(c,x+141+j*37,620,27,12,j<l.ammo?green:border,true);
   if(l.reload>0)rect(c,x+141,597,101*(float)(1-l.reload/90),2,green,true);
   buttons.add(new Btn(x,570,270,73,"l"+i,true));}
   rect(c,866,570,394,73,border,false);text(c,fmt("READY %02d   RESERVE %02d",game.ready(),game.reserve),883,597,18,green);text(c,fmt("%d allocated / 90s per full reload",game.reserved),883,623,13,muted);
  }
  void overlay(Canvas c){rect(c,0,0,1280,720,0xee000000,true);rect(c,190,69,900,580,panel,true);rect(c,190,69,900,580,green,false);buttons.clear();String title=game.finished?(game.won?"MISSION COMPLETE":"BATTERY OVERRUN"):help?"OPERATOR GUIDE":started?"MISSION PAUSED":"AIR DEFAME 101";text(c,title,225,118,30,green);
   if(game.finished){text(c,fmt("COMMAND SITE %d%% / SCORE %d",game.health,game.score),225,170,23,amber);text(c,fmt("%d intercepts   %d missiles fired   %d leaks",game.kills,game.shots,game.leaks),225,208,19,green);text(c,"DEBRIEF / CONFIRMED AIRCRAFT",225,249,16,muted);int i=0;for(Game.Contact t:game.contacts){int col=i/6,row=i%6;text(c,fmt("%03d %-9s %s",t.id,Game.NAMES[t.type],t.alive?"UNRESOLVED":t.outcome),225+col*421,278+row*32,13,muted);i++;}text(c,"BEST SCORE "+best,225,505,17,amber);}
   else{String[] rows={"Defend the command site through 12 incoming aircraft.","1. Select a radar contact. Two sweeps establish a track.","2. Check estimated identity, altitude, speed and range.","3. TRACK, then LOCK the target. FIRE inside the envelope.","4. Keep illumination active until intercept or miss.","", "Only TWO targets can be illuminated. RELEASE CH frees one.","Release risks missiles in flight. Low terrain can break guidance.","Select L1 / L2 / L3 below the radar to choose a launcher.","Empty launchers reload automatically: 90 simulation seconds.","9 ready + 9 reserve. A partially used launcher cannot reload.","25 km missile limit / 13,700 m ceiling / 40 km initial radar range.","1x, 2x and 4x accelerate the entire mission, including reloads."};for(int i=0;i<rows.length;i++)text(c,rows[i],225,163+i*27,15,i==0?amber:muted);}
   button(c,"start",started&&!game.finished?"RESUME MISSION":"START MISSION",225,558,270,true);button(c,"sound",sound?"SOUND ON":"SOUND OFF",510,558,240,true);if(started&&!game.finished)button(c,"restart","RESTART",765,558,285,true);button(c,"menu","MAIN MENU",765,615,285,true);
  }
  @Override public boolean onTouchEvent(MotionEvent e){if(e.getAction()!=MotionEvent.ACTION_UP)return true;float x=(e.getX()-ox)/scale,y=(e.getY()-oy)/scale;for(Btn b:buttons)if(b.enabled&&b.r.contains(x,y)){act(b.id);performClick();invalidate();return true;}if(started&&!paused&&!game.finished){Game.Contact pick=null;double near=30;for(Game.Contact t:game.contacts)if(game.visible(t)){double d=Math.hypot(x-(595+t.px/game.range*183),y-(302+t.py/game.range*183));if(d<near){near=d;pick=t;}}if(pick!=null){selected=pick;notice="TRACK "+pick.id+" SELECTED / "+game.trackState(pick);beep();}}invalidate();return true;}
  public boolean performClick(){super.performClick();return true;}
  void act(String id){if(id.equals("start")){if(!started||game.finished){game.start();selected=null;started=true;ended=false;speed=1;}paused=help=false;last=System.nanoTime();notice="SEARCH ACTIVE / TWO SWEEPS TO ESTABLISH TRACK";}
   else if(id.equals("restart")){game.start();selected=null;ended=false;paused=help=false;speed=1;notice="NEW MISSION STARTED";}
   else if(id.equals("pause")){paused=true;help=false;}
   else if(id.equals("help")){paused=true;help=true;}
   else if(id.equals("sound"))sound=!sound;
   else if(id.equals("speed")){speed=speed==1?2:speed==2?4:1;notice="SIMULATION SPEED "+speed+"x / ALL TIMERS ACCELERATE";}
   else if(id.equals("range")){game.cycleRange();notice="RADAR DISPLAY RANGE "+game.range+" km";}
   else if(id.equals("next")){selected=game.nextTarget(selected);notice=selected==null?"NO DETECTED AIRCRAFT / WAIT FOR SWEEP":"TARGET "+selected.id+" SELECTED";}
   else if(id.equals("track"))notice=game.track(selected);
   else if(id.equals("menu")){started=false;paused=false;game.running=false;selected=null;}
   else if(id.equals("illuminate"))notice=game.illuminate(selected);
   else if(id.equals("release"))notice=game.release(selected);
   else if(id.equals("launch"))notice=game.launch(selected);
   else if(id.matches("l[012]")){game.chosenLauncher=Integer.parseInt(id.substring(1));notice="LAUNCHER "+(game.chosenLauncher+1)+" SELECTED";}
   syncMusic();beep();
  }
 }
}
