package com.jb.radar;
import android.graphics.*;import android.view.MotionEvent;import java.util.*;import java.io.File;import javax.imageio.ImageIO;
/** Historical v0.16 preview harness. First-observation lock assertions are superseded
 * by RebuildUIRenderCheck; do not include this in current verification runs. */
public class AutoTrackingRenderCheck {
 static void ok(boolean b,String m){if(!b)throw new AssertionError(m);}
 static class Recording extends Canvas {ArrayList<String> labels=new ArrayList<>();public void drawText(String s,float x,float y,Paint p){labels.add(s);super.drawText(s,x,y,p);}}
 static Recording draw(MainActivity.Radar v,String name)throws Exception{Recording c=new Recording();v.last=0;v.onDraw(c);if(name!=null)ImageIO.write(c.image,"png",new File("out/"+name+".png"));return c;}
 static void tap(MainActivity.Radar v,final float x,final float y)throws Exception{draw(v,null);v.onTouchEvent(new MotionEvent(){public float getX(){return x;}public float getY(){return y;}});}
 public static void main(String[] args)throws Exception{MainActivity a=new MainActivity();a.onCreate(null);a.onResume();MainActivity.Radar v=a.view;v.act("start");v.act("introskip");Properties p=new Properties();p.setProperty("radar.tracks","3");v.equipment=new Equipment(p);v.game=new Game(1,v.economy,v.equipment);Game g=v.game;g.start();g.contacts.clear();g.elapsed=1;g.random=new Random(0){public double nextDouble(){return 0;}public double nextGaussian(){return 0;}};
  for(int i=0;i<5;i++){Game.Contact t=new Game.Contact();t.id=i+1;t.type=0;double angle=i*1.1;t.x=Math.sin(angle)*(5+3*i);t.y=-Math.cos(angle)*(5+3*i);t.alt=3000;t.speed=720;t.heading=angle+Math.PI;t.weapon=-1;g.contacts.add(t);g.observe(t);t.confidence=i%2==0?.8:.4;}
  Game.EnemyMissile m=new Game.EnemyMissile();m.id=101;m.weapon=4;m.x=18;m.z=3;m.alt=3000;m.speed=.5;m.flight.vx=-1;g.enemyMissiles.add(m);g.observe(m);ok(g.trackedCount()==3,"configured track capacity");Game.Contact chosen=g.contacts.get(3);v.choose(chosen);g.elapsed=4;Recording c=draw(v,"auto-detected-v016");ok(c.labels.stream().anyMatch(s->s.contains("ALT ---"))&&c.labels.stream().anyMatch(s->s.contains("SPD ---")&&s.contains("HDG ---")),"untracked altitude/speed/direction masked in actual Canvas");ok(v.buttons.stream().noneMatch(b->b.id.equals("track"))&&v.buttons.stream().anyMatch(b->b.id.equals("prioritize")),"TRACK removed / PRIORITIZE present");int seen=chosen.samples;tap(v,1030,170);ok(g.tracked(chosen)&&chosen.priority&&g.trackedCount()==3&&chosen.samples==seen&&!g.hardLocked(chosen),"prioritize assigns without measurement refresh or hard lock");draw(v,"auto-tracked-v016");
  v.choose(null);tap(v,(float)(595+g.displayX(chosen)/g.range*183),(float)(302+g.displayY(chosen)/g.range*183));ok(v.selected==chosen,"tap uses predicted position");tap(v,1030,230);ok(g.hardLocked(chosen),"LOCK separate button");draw(v,"auto-locked-v016");g.elapsed=11;chosen.alt=20;g.observe(chosen);g.maintainTracks();c=draw(v,"auto-stale-v016");ok(c.labels.stream().anyMatch(s->s.startsWith("STALE / LAST SEEN"))&&!g.hardLocked(chosen),"stale readout and lost lock");ok(v.buttons.stream().noneMatch(b->b.id.equals("launch")&&b.enabled),"FIRE disabled with stale data");
  v.act("help");draw(v,"auto-guide-v016");a.onDestroy();System.out.println("PASS: Canvas untracked masking, capacity display, PRIORITIZE touch, predicted hit-testing, separate lock, stale labels/FIRE gate and operator guide");
 }
}
