package com.jb.radar;
import android.graphics.Canvas;import javax.imageio.ImageIO;import java.io.File;
public class IntroRenderCheck {
 static void ok(boolean b,String s){if(!b)throw new AssertionError(s);}
 static void draw(MainActivity.Radar v,String name)throws Exception{Canvas c=new Canvas();v.onDraw(c);if(name!=null)ImageIO.write(c.image,"png",new File("out/"+name+".png"));}
 public static void main(String[] args)throws Exception{
  MainActivity a=new MainActivity();a.onCreate(null);a.onResume();MainActivity.Radar v=a.view;v.act("start");
  ok(v.intro.active&&!v.started&&!v.game.running&&v.game.contacts.isEmpty()&&v.game.elapsed==0,"mission untouched during intro");ok(!a.menuMusic.isPlaying()&&a.introAudio.player.isPlaying(),"intro audio replaces menu");draw(v,"intro-v013-start");
  for(int n=0;n<12;n++){a.introAudio.player.position=(int)Math.ceil((v.intro.reveal[n][v.intro.reveal[n].length-1]+.1)*1000);draw(v,"intro-v013-"+(n+1));ok(v.intro.section()==n,"section order");for(int i=0;i<v.introScene.xs[n].length;i++){ok(v.introScene.xs[n][i]>=80&&v.introScene.xs[n][i]<=1190,"text fits width");ok(v.introScene.ys[n][i]<600,"text above controls");}ok(v.game.elapsed==0&&v.game.contacts.isEmpty(),"no early enemy activity");ok(v.buttons.size()==3,"three controls always visible");}
  a.introAudio.player.position=74500;draw(v,null);v.act("intropause");double at=v.intro.elapsed;ok(v.intro.paused&&!a.introAudio.player.isPlaying(),"pause stops music");v.last=System.nanoTime()-100000000000L;draw(v,null);ok(v.intro.elapsed==at,"paused text cannot jump");a.onPause();a.onResume();draw(v,null);ok(v.intro.paused&&v.intro.elapsed==at&&!a.introAudio.player.isPlaying(),"manual pause survives background");v.act("intropause");ok(a.introAudio.player.isPlaying(),"resume music");a.onPause();ok(!a.introAudio.player.isPlaying(),"background stops music");a.onResume();draw(v,null);ok(v.intro.elapsed==at&&a.introAudio.player.isPlaying(),"foreground resumes same position");v.act("intromusic");ok(a.introAudio.player.volume==0&&a.introAudio.player.isPlaying(),"mute keeps score synchronized");v.act("intromusic");ok(a.introAudio.player.volume==.65f,"restore 65 percent volume");a.focusListener.onAudioFocusChange(-1);ok(!a.introAudio.player.isPlaying(),"focus loss pauses");a.focusListener.onAudioFocusChange(1);ok(a.introAudio.player.isPlaying(),"focus gain resumes");
  a.introAudio.player.position=76000;draw(v,"intro-v013-radar");ok(!v.intro.active&&v.started&&v.game.running&&v.game.elapsed==0,"natural transition starts radar at zero");ok(a.introAudio.player==null,"completion releases music");
  v.act("restart");ok(v.intro.active&&v.intro.elapsed==0&&a.introAudio.player.position==0&&!v.game.running,"replay resets both");v.act("introskip");ok(v.started&&v.game.running&&v.game.elapsed==0&&a.introAudio.player==null,"skip immediate direct radar");
  v.act("menu");v.act("start");a.introAudio.failed=true;a.introAudio.ready=false;v.last=System.nanoTime()-1000000000L;draw(v,null);ok(v.intro.elapsed>.9,"audio failure progresses silently");v.act("introskip");a.onDestroy();System.out.println("PASS: 12-section Digital-7 layouts, controls, mission gating, 65% audio, pause/background/focus, mute, skip, completion, replay and audio failure fallback");
 }
}
