package com.jb.radar;
import android.graphics.*;import android.view.MotionEvent;import java.util.*;import java.io.File;import javax.imageio.ImageIO;
public class RebuildUIRenderCheck {
 static void ok(boolean b,String m){if(!b)throw new AssertionError(m);}
 static class Recording extends Canvas {ArrayList<String> labels=new ArrayList<>();int lines;public void drawText(String s,float x,float y,Paint p){labels.add(s);super.drawText(s,x,y,p);}public void drawLine(float x,float y,float xx,float yy,Paint p){lines++;super.drawLine(x,y,xx,yy,p);}}
 static Recording draw(MainActivity.Radar v,String name)throws Exception{Recording c=new Recording();v.last=0;v.onDraw(c);if(name!=null)ImageIO.write(c.image,"png",new File("out/"+name+".png"));return c;}
 static void tap(MainActivity.Radar v,String id)throws Exception{draw(v,null);MainActivity.Radar.Btn found=null;for(MainActivity.Radar.Btn b:v.buttons)if(b.id.equals(id))found=b;ok(found!=null,"control exists: "+id);final float x=(found.r.l+found.r.r)/2,y=(found.r.t+found.r.b)/2;v.onTouchEvent(new MotionEvent(){public float getX(){return x;}public float getY(){return y;}});}
 static boolean enabled(MainActivity.Radar v,String id){for(MainActivity.Radar.Btn b:v.buttons)if(b.id.equals(id))return b.enabled;return false;}
 static boolean has(Recording c,String s){for(String l:c.labels)if(l.contains(s))return true;return false;}
 static Game.Contact detected(Game g,int id,double x,double y){Game.Contact t=new Game.Contact();t.id=id;t.type=0;t.x=x;t.y=y;t.alt=3000;t.speed=720;t.heading=0;t.weapon=-1;g.contacts.add(t);g.observe(t);return t;}
 static void clear(Game g){g.contacts.clear();g.enemyMissiles.clear();g.missiles.clear();g.elapsed=1;g.random=new Random(0){public double nextDouble(){return 0;}public double nextGaussian(){return 0;}};}
 static void stable(Game g,Game.Contact t){g.elapsed+=1;t.y+=.2;g.observe(t);ok(g.stableTrack(t),"fixture stable");}
 public static void main(String[] args)throws Exception{
  MainActivity a=new MainActivity();a.onCreate(null);a.onResume();MainActivity.Radar v=a.view;
  tap(v,"playmodes");tap(v,"storymode");tap(v,"missionloadout");Recording c=draw(v,"loadout-v017");ok(has(c,"MIM-303 Sentinel")&&has(c,"FIM-306 Ember"),"all own guidance classes in loadout");ok(!has(c,"Kh-")&&!has(c,"Su-"),"loadout does not expose enemy roster");ok(!enabled(v,"loadout:stonebolt")&&enabled(v,"loadout:active")&&enabled(v,"loadout:ir6"),"Stonebolt paid, test-ready guided choices owned");tap(v,"loadout:active");tap(v,"missiondeploy");ok(v.intro.active&&!v.game.running,"no gameplay before intro");tap(v,"introskip");ok(v.game.weapon.id.equals("active")&&!v.game.irMode,"active missile loadout actually deployed");Game g=v.game;clear(g);
  Game.Contact t=detected(g,1,0,-12);v.choose(t);c=draw(v,"acquiring-v017");ok(has(c,"ACQUIRING")&&has(c,"SPD ---")&&has(c,"HDG ---"),"acquisition state hides unmeasured motion");ok(!enabled(v,"illuminate")&&!enabled(v,"launch"),"weak acquisition cannot lock or fire");stable(g,t);c=draw(v,"stable-v017");ok(has(c,"STABLE")&&has(c,"ILLUMINATION 0/2")&&has(c,"MIDCOURSE 0/2"),"stable state and independent counters");tap(v,"launch");tap(v,"launch");draw(v,null);ok(g.midcourseUsed()==2&&g.illuminationUsed()==0&&!enabled(v,"launch"),"ARH two missiles exhaust only midcourse capacity");Game.Missile m=g.missiles.get(0);ok(v.selectedSupport()==m,"oldest selected supported missile identified");c=draw(v,"support-v017");ok(has(c,"RELEASE M01"),"support release identifies affected missile");tap(v,"releasesupport");ok(m.supportReleased&&g.midcourseUsed()==1,"explicit release frees only one link");tap(v,"guidancelines");ok(!v.guidanceLines,"overlay toggle");tap(v,"guidancelines");ok(v.guidanceLines,"overlay restore");
  tap(v,"illuminate");ok(g.hardLocked(t),"separate radar lock even active loadout");Game.Contact other=detected(g,2,7,-8);v.choose(other);ok(g.hardLocked(t),"selection does not release previous illumination");v.choose(t);tap(v,"release");ok(!g.hardLocked(t)&&g.tracked(t),"UNLOCK preserves track");g.elapsed+=g.freshSeconds()+.2;g.maintainTracks();c=draw(v,"coasting-v017");ok(has(c,"COASTING")&&has(c,"LAST UPDATE")&&!enabled(v,"launch"),"coasting age and fire disabled");g.elapsed=t.seen+g.trackExpiry()+.1;g.maintainTracks();c=draw(v,"lost-v017");ok(has(c,"LOST")&&has(c,"ALT ---"),"lost last known plot and masked details");
  v.act("menu");tap(v,"equipment");c=draw(v,"equipment-v017");ok(has(c,"IRST sensor")&&has(c,"NOT FITTED")&&has(c,"Midcourse channels"),"equipment separates IRST and channel resources");for(int i=0;i<4;i++){c=draw(v,null);ok(!has(c,"Kh-"),"equipment browsing hides enemy weapons");tap(v,"equipnext");}tap(v,"equipmentback");tap(v,"techtree");c=draw(v,"tree-v017");ok(has(c,"MIM-303 Sentinel")&&has(c,"FIM-306 Ember"),"four-card tech tree");tap(v,"treeback");tap(v,"playmodes");tap(v,"storymode");tap(v,"missionloadout");tap(v,"loadout:ir6");tap(v,"missiondeploy");tap(v,"introskip");g=v.game;clear(g);t=detected(g,1,0,-3);v.choose(t);draw(v,null);ok(v.game.irMode&&enabled(v,"illuminate")&&!v.equipment.radar.infrared,"IR seeker control available without IRST");tap(v,"illuminate");for(int i=0;i<90;i++)g.ir.tick(.05);ok(g.ir.locked,"IR seeker fixture acquired");c=draw(v,"infrared-v017");ok(has(c,"IR SEEKER LOCKED")&&has(c,"IR LOCK")&&enabled(v,"launch"),"IR-specific feedback and launch enable");tap(v,"launch");ok(g.ready()==8&&g.missiles.get(0).infrared&&g.midcourseUsed()==0&&g.illuminationUsed()==0,"IR uses equipped launcher without channels");tap(v,"l1");ok(g.irMode&&g.chosenLauncher==1,"launcher selection cannot change equipped guidance");
  v.act("help");draw(v,"guide-v017");a.onDestroy();System.out.println("PASS: four-weapon loadout, no enemy spoilers, acquiring/stable/coasting/lost UI, independent counters, explicit support release, preserved lock, line toggle, IR without IRST, equipment and tree touch navigation");
 }
}
