package com.jb.radar;
import android.graphics.*;import android.view.MotionEvent;import java.util.*;import java.io.File;import javax.imageio.ImageIO;
/** v0.19 reference-layout touch and sensor-rendering integration checks. */
public class ReferenceUIRenderCheck {
 static void ok(boolean b,String s){if(!b)throw new AssertionError(s);}
 static class Recording extends Canvas {ArrayList<String> labels=new ArrayList<>();int lines;public void drawText(String s,float x,float y,Paint p){labels.add(s);super.drawText(s,x,y,p);}public void drawLine(float x,float y,float xx,float yy,Paint p){lines++;super.drawLine(x,y,xx,yy,p);}}
 static Recording draw(MainActivity.Radar v,String name)throws Exception{v.last=0;Recording c=new Recording();v.onDraw(c);if(name!=null)ImageIO.write(c.image,"png",new File("out/"+name+".png"));return c;}
 static void tap(MainActivity.Radar v,String id)throws Exception{draw(v,null);MainActivity.Radar.Btn found=null;for(MainActivity.Radar.Btn b:v.buttons)if(b.id.equals(id))found=b;ok(found!=null,"button present "+id);final float x=(found.r.l+found.r.r)/2,y=(found.r.t+found.r.b)/2;v.onTouchEvent(new MotionEvent(){public float getX(){return x;}public float getY(){return y;}});}
 static boolean has(Recording c,String s){for(String l:c.labels)if(l.contains(s))return true;return false;}
 static boolean enabled(MainActivity.Radar v,String id){for(MainActivity.Radar.Btn b:v.buttons)if(b.id.equals(id))return b.enabled;return false;}
 static void clear(Game g){g.contacts.clear();g.enemyMissiles.clear();g.missiles.clear();g.elapsed=1;g.nextSpawn=999;g.random=new Random(0){public double nextDouble(){return 0;}public double nextGaussian(){return 0;}};}
 static Game.Contact target(Game g,int id,double x,double y){Game.Contact t=new Game.Contact();t.id=id;t.type=0;t.x=x;t.y=y;t.alt=3000;t.desiredAlt=2920;t.speed=720;t.heading=0;t.weapon=-1;g.contacts.add(t);g.observe(t);return t;}
 static void stable(Game g){g.elapsed+=1;for(Game.Contact t:g.contacts){t.y+=.2;g.observe(t);}g.maintainTracks();}
 public static void main(String[] args)throws Exception{MainActivity a=new MainActivity();a.onCreate(null);a.onResume();MainActivity.Radar v=a.view;for(String filename:RadarIcons.FILES)ok(v.radarIcons.loaded(filename),"canonical icon loaded "+filename);
  tap(v,"playmodes");tap(v,"storymode");tap(v,"missionloadout");draw(v,"loadout-v019");tap(v,"loadout:active");tap(v,"missiondeploy");tap(v,"introskip");Game g=v.game;clear(g);ok(g.launchers.length==4&&g.ready()==12&&g.reserve==12,"four launchers with preserved profile capacity");
  Game.Contact t=target(g,1,-5,-10);v.choose(t);Recording c=draw(v,"acquiring-v019");ok(has(c,"SPD ---")&&has(c,"HDG ---"),"one detection does not expose motion");Game.Contact hostile=target(g,2,6,-12),friendly=target(g,3,12,9),unknown=target(g,4,-17,9),hostileGeneric=target(g,5,20,9),untracked=target(g,6,-21,-15);stable(g);g.identifyAllegiance(hostile,Game.Allegiance.HOSTILE,"TEST");hostile.recognizedType="Su-25";g.identifyAllegiance(friendly,Game.Allegiance.FRIENDLY,"TEST");friendly.recognizedType="FRIENDLY AIRCRAFT";unknown.recognizedType="Su-25";g.identifyAllegiance(hostileGeneric,Game.Allegiance.HOSTILE,"TEST");hostileGeneric.recognizedType="";
  ok(v.iconName(hostile).equals("hostile_jet.png")&&v.iconName(friendly).equals("friendly_jet.png"),"recognized affiliation icon mapping");ok(v.iconName(unknown).equals("unknown_track.png"),"recognized type does not establish allegiance");ok(v.iconName(hostileGeneric).equals("hostile_no_ID.png")&&v.iconName(untracked).equals("Unknown_untracked_target.png"),"generic and untracked icon mapping");v.choose(untracked);c=draw(v,"untracked-v019");ok(has(c,"ALT ---")&&has(c,"SPD ---")&&!g.tracked(untracked),"untracked masking");ok(!v.displayStale(untracked),"fresh detection outside tracking capacity stays fresh");v.choose(t);c=draw(v,"radar-reference-v019");ok(has(c,"TRACK LIST / TWS")&&has(c,"SELECTED MISSILE")&&has(c,"SENSORS")&&has(c,"SELECTED TARGET")&&has(c,"LAUNCHER 4")&&has(c,"BATTLE LOG"),"reference panel hierarchy");ok(has(c,"DATALINKS")&&enabled(v,"launch"),"shared-capacity feedback and tracked active launch");
  double seen=t.seen;tap(v,"range:10");ok(g.range==10&&t.seen==seen,"range button changes view only");tap(v,"range:30");tap(v,"l3");ok(g.chosenLauncher==3,"fourth launcher selectable");tap(v,"launch");tap(v,"launch");ok(g.channels()==2&&g.launchers[3].ammo==1,"shared channel consumption");tap(v,"launch");ok(v.fireConfirm&&g.missiles.size()==2&&g.ready()==10,"overflow first click does not launch");c=draw(v,"channel-confirm-v019");ok(has(c,"TRANSFER")&&has(c,"SEARCH EARLY"),"overflow consequence displayed");tap(v,"cancelfire");ok(!v.fireConfirm&&g.ready()==10,"cancel keeps ammunition");tap(v,"launch");tap(v,"confirmfire");ok(!v.fireConfirm&&g.missiles.size()==3&&g.ready()==9&&g.missiles.get(0).seekerState==Game.SeekerState.SEARCHING,"confirmed oldest displacement and launch");
  Equipment.Weapon launched=g.missiles.get(2).profile;tap(v,"weaponnext");ok(g.weapon.guidance==Equipment.Guidance.INFRARED&&g.missiles.get(2).profile==launched,"owned missile selector preserves in-flight profile");tap(v,"weaponnext");ok(g.weapon==v.equipment.primary,"locked Stonebolt excluded from selector");tap(v,"illuminate");ok(g.lockAcquiring(t)&&!g.hardLocked(t),"timed lock UI starts acquisition");for(int i=0;i<22;i++)g.tick(.1);g.observe(t);g.maintainTracks();ok(g.hardLocked(t),"timed lock resolves");c=draw(v,"locked-v019");tap(v,"release");ok(!g.hardLocked(t)&&g.tracked(t),"explicit unlock preserves track");
  tap(v,"autotrack");ok(!g.autoTrack,"auto track toggle");seen=t.seen;g.elapsed+=1;g.observe(t);ok(t.seen==seen,"auto off leaves track estimate frozen");tap(v,"autotrack");tap(v,"radar");ok(g.radarSwitchAt>=0&&!g.radarDesired,"radar shutdown delay displayed");for(int i=0;i<30;i++)g.tick(.1);ok(!g.radarReady(),"radar off after configured delay");int contacts=g.contacts.size(),missiles=g.missiles.size(),ready=g.ready();tap(v,"reset");ok(g.contacts.size()==contacts&&g.missiles.size()==missiles&&g.ready()==ready&&!g.detected(t),"RESET affects sensor state, not world or ammo");draw(v,"radar-off-v019");tap(v,"battlelog");c=draw(v,"battle-log-v019");ok(v.logOpen&&v.paused&&has(c,"RADAR"),"expand log pauses and shows events");tap(v,"logback");ok(!v.logOpen&&!v.paused,"log return resumes");tap(v,"status");draw(v,"battery-v019");ok(v.statusOpen,"battery status opens with seven components");v.act("start");v.act("help");draw(v,"guide-v019");v.act("start");
  // Controlled compatible sensor profile: no radar range or motion is exposed for passive-only tracks.
  Properties passive=new Properties();passive.setProperty("radar.infrared","true");Equipment ep=new Equipment(passive);Economy ew=new Economy(new Economy.MemoryStore());ew.equip("ir6");v.equipment=ep;v.economy=ew;v.game=new Game(18,ew,ep);g=v.game;g.start();clear(g);g.radarOn=g.radarDesired=false;t=target(g,20,0,-3);v.choose(t);tap(v,"irst");for(int i=0;i<80;i++){g.elapsed+=.1;g.ir.tick(.1);}ok(g.ir.irstTracked(t)&&!g.detected(t),"passive fixture acquired without radar");c=draw(v,"irst-only-v019");ok(has(c,"RANGE UNKNOWN")&&has(c,"ALT ---")&&has(c,"SPD ---")&&!has(c,"Infinity"),"passive UI has bearing-only data");ok(enabled(v,"launch"),"IRST cue enables IR LOAL without prelaunch lock");tap(v,"launch");ok(g.missiles.size()==1&&g.channels()==0&&g.missiles.get(0).seekerState==Game.SeekerState.SEARCHING,"passive launch searches with no channel");Recording lines=new Recording();v.guidanceLine(lines,g.missiles.get(0),0,0,10,10,100);ok(lines.lines==0,"IR guidance lines suppressed");tap(v,"radar");for(int i=0;i<35;i++){g.elapsed+=.1;g.sensorTick();g.ir.tick(.1);}tap(v,"cueradar");ok(t.radarCuePending&&!g.detected(t),"IRST radar cue does not create radar measurements");tap(v,"reset");ok(g.ir.irstTracked(t),"reset keeps independent passive track");a.onDestroy();System.out.println("PASS: reference panel layout, canonical affiliation/recognition icons, masked sensor data, 4th launcher, range-only scaling, owned weapon cycling, timed lock, overflow confirmation, radar/auto/reset, battle log and battery UI");
 }
}
