package com.jb.radar;
import android.graphics.*;import android.content.SharedPreferences;import javax.imageio.ImageIO;import java.io.File;
public class TechTreeRenderCheck {
 static void ok(boolean b,String s){if(!b)throw new AssertionError(s);}
 static void draw(MainActivity.Radar v,String name)throws Exception{v.last=0;Canvas c=new Canvas();v.onDraw(c);ImageIO.write(c.image,"png",new File("out/"+name+".png"));}
 public static void main(String[] args)throws Exception{
  MainActivity app=new MainActivity();app.getPreferences(0).edit().putInt("hawk_best",9999).putLong("economy_dollars",2400).putLong("economy_bp",800).commit();app.onCreate(null);app.onResume();MainActivity.Radar v=app.view;
  ok(!v.profileFallback&&v.economy.snapshot().dollars==2400&&v.economy.snapshot().bp==800,"legacy balance migration / asset load");draw(v,"menu-v09");v.act("techtree");ok(v.treeOpen&&app.menuMusic.isPlaying(),"tech tree opens with menu audio");draw(v,"usa-tree-v09");v.act("node:watchpost");draw(v,"watchpost-v09");v.act("node:stonebolt");SharedPreferences.failWrites=true;v.act("research");ok(v.economy.saveFailed&&v.economy.snapshot().bp==800,"failed research rolls back UI balance");draw(v,"tech-save-failed-v09");SharedPreferences.failWrites=false;v.act("retrysave");v.act("research");ok(v.economy.snapshot().bp==200&&TechTree.researched(v.economy.snapshot(),TechTree.STONEBOLT),"UI spends BP / saves research");draw(v,"stonebolt-researched-v09");v.act("purchase");ok(v.economy.snapshot().dollars==900&&v.economy.snapshot().owned.contains("stonebolt"),"UI purchases with Dollars");v.act("equip");draw(v,"stonebolt-equipped-v09");app.onBackPressed();ok(!v.treeOpen&&!v.started,"back returns to menu");v.act("equipment");draw(v,"equipment-v09");v.act("equipnext");draw(v,"equipment-stonebolt-v09");app.onBackPressed();v.act("start");v.act("introskip");ok(v.game.weapon.id.equals("stonebolt")&&!app.menuMusic.isPlaying(),"equipped missile starts / menu audio stops");for(int i=0;i<1800;i++)v.game.tick(.05);for(Game.Contact t:v.game.contacts)if(v.game.liveTrack(t)){v.choose(t);v.game.track(t);v.game.illuminate(t);break;}draw(v,"gameplay-v09");v.act("help");draw(v,"guide-v09");v.act("menu");ok(app.menuMusic.isPlaying(),"menu audio returns");app.onPause();ok(!app.menuMusic.isPlaying(),"background pauses music");app.onDestroy();
  app=new MainActivity();app.onCreate(null);app.onResume();v=app.view;ok(v.best==9999&&v.economy.snapshot().dollars==900&&v.economy.snapshot().bp==200&&v.economy.snapshot().equippedMissile.equals("stonebolt"),"all balances, ownership and equipped state survive Activity recreation");v.act("techtree");v.act("node:rampart");v.act("equip");v.act("treeback");v.act("start");v.act("introskip");ok(v.game.weapon.id.equals("rampart"),"can switch back to free missile");v.act("menu");app.focusListener.onAudioFocusChange(-1);ok(!app.menuMusic.isPlaying(),"focus loss pauses music");app.focusListener.onAudioFocusChange(1);ok(app.menuMusic.isPlaying(),"focus regain resumes music");app.onDestroy();System.out.println("PASS: tech tree research/purchase/equip UI, preference migration/recreation, save retry, stats/guide layout and music lifecycle");
 }
}
